/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.scoutsfev.cudu.dd.tables.Cargo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CargoRecord extends UpdatableRecordImpl<CargoRecord> implements Record5<Integer, String, String, Boolean, Integer> {

	private static final long serialVersionUID = 302619464;

	/**
	 * Setter for <code>public.cargo.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.cargo.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.cargo.etiqueta</code>.
	 */
	public void setEtiqueta(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.cargo.etiqueta</code>.
	 */
	public String getEtiqueta() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.cargo.ambito</code>.
	 */
	public void setAmbito(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.cargo.ambito</code>.
	 */
	public String getAmbito() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.cargo.unico</code>.
	 */
	public void setUnico(Boolean value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.cargo.unico</code>.
	 */
	public Boolean getUnico() {
		return (Boolean) getValue(3);
	}

	/**
	 * Setter for <code>public.cargo.puntos</code>.
	 */
	public void setPuntos(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.cargo.puntos</code>.
	 */
	public Integer getPuntos() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Boolean, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, Boolean, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Cargo.CARGO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Cargo.CARGO.ETIQUETA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Cargo.CARGO.AMBITO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field4() {
		return Cargo.CARGO.UNICO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Cargo.CARGO.PUNTOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getEtiqueta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getAmbito();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value4() {
		return getUnico();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getPuntos();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CargoRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CargoRecord value2(String value) {
		setEtiqueta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CargoRecord value3(String value) {
		setAmbito(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CargoRecord value4(Boolean value) {
		setUnico(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CargoRecord value5(Integer value) {
		setPuntos(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CargoRecord values(Integer value1, String value2, String value3, Boolean value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CargoRecord
	 */
	public CargoRecord() {
		super(Cargo.CARGO);
	}

	/**
	 * Create a detached, initialised CargoRecord
	 */
	public CargoRecord(Integer id, String etiqueta, String ambito, Boolean unico, Integer puntos) {
		super(Cargo.CARGO);

		setValue(0, id);
		setValue(1, etiqueta);
		setValue(2, ambito);
		setValue(3, unico);
		setValue(4, puntos);
	}
}
