/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.dd.tables.DtoActividadDetalle;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoActividadDetalleRecord extends TableRecordImpl<DtoActividadDetalleRecord> implements Record12<String, Integer, String, Integer, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, String> {

	private static final long serialVersionUID = -115101296;

	/**
	 * Setter for <code>public.dto_actividad_detalle.grupo_id</code>.
	 */
	public void setGrupoId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.grupo_id</code>.
	 */
	public String getGrupoId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.actividad_id</code>.
	 */
	public void setActividadId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.actividad_id</code>.
	 */
	public Integer getActividadId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.estado_asistente</code>.
	 */
	public void setEstadoAsistente(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.estado_asistente</code>.
	 */
	public String getEstadoAsistente() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.asociado_id</code>.
	 */
	public void setAsociadoId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.asociado_id</code>.
	 */
	public Integer getAsociadoId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.nombre_completo</code>.
	 */
	public void setNombreCompleto(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.nombre_completo</code>.
	 */
	public String getNombreCompleto() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.tipo</code>.
	 */
	public void setTipo(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.tipo</code>.
	 */
	public String getTipo() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.rama_colonia</code>.
	 */
	public void setRamaColonia(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.rama_colonia</code>.
	 */
	public Boolean getRamaColonia() {
		return (Boolean) getValue(6);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.rama_manada</code>.
	 */
	public void setRamaManada(Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.rama_manada</code>.
	 */
	public Boolean getRamaManada() {
		return (Boolean) getValue(7);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.rama_exploradores</code>.
	 */
	public void setRamaExploradores(Boolean value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.rama_exploradores</code>.
	 */
	public Boolean getRamaExploradores() {
		return (Boolean) getValue(8);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.rama_expedicion</code>.
	 */
	public void setRamaExpedicion(Boolean value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.rama_expedicion</code>.
	 */
	public Boolean getRamaExpedicion() {
		return (Boolean) getValue(9);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.rama_ruta</code>.
	 */
	public void setRamaRuta(Boolean value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.rama_ruta</code>.
	 */
	public Boolean getRamaRuta() {
		return (Boolean) getValue(10);
	}

	/**
	 * Setter for <code>public.dto_actividad_detalle.telefono</code>.
	 */
	public void setTelefono(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.dto_actividad_detalle.telefono</code>.
	 */
	public String getTelefono() {
		return (String) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<String, Integer, String, Integer, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, String> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<String, Integer, String, Integer, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, String> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.GRUPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.ACTIVIDAD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.ESTADO_ASISTENTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.ASOCIADO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.NOMBRE_COMPLETO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.TIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.RAMA_COLONIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field8() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.RAMA_MANADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field9() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.RAMA_EXPLORADORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field10() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.RAMA_EXPEDICION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field11() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.RAMA_RUTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field12() {
		return DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE.TELEFONO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getGrupoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getActividadId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getEstadoAsistente();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getAsociadoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getNombreCompleto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getRamaColonia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value8() {
		return getRamaManada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value9() {
		return getRamaExploradores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value10() {
		return getRamaExpedicion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value11() {
		return getRamaRuta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value12() {
		return getTelefono();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value1(String value) {
		setGrupoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value2(Integer value) {
		setActividadId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value3(String value) {
		setEstadoAsistente(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value4(Integer value) {
		setAsociadoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value5(String value) {
		setNombreCompleto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value6(String value) {
		setTipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value7(Boolean value) {
		setRamaColonia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value8(Boolean value) {
		setRamaManada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value9(Boolean value) {
		setRamaExploradores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value10(Boolean value) {
		setRamaExpedicion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value11(Boolean value) {
		setRamaRuta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord value12(String value) {
		setTelefono(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoActividadDetalleRecord values(String value1, Integer value2, String value3, Integer value4, String value5, String value6, Boolean value7, Boolean value8, Boolean value9, Boolean value10, Boolean value11, String value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DtoActividadDetalleRecord
	 */
	public DtoActividadDetalleRecord() {
		super(DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE);
	}

	/**
	 * Create a detached, initialised DtoActividadDetalleRecord
	 */
	public DtoActividadDetalleRecord(String grupoId, Integer actividadId, String estadoAsistente, Integer asociadoId, String nombreCompleto, String tipo, Boolean ramaColonia, Boolean ramaManada, Boolean ramaExploradores, Boolean ramaExpedicion, Boolean ramaRuta, String telefono) {
		super(DtoActividadDetalle.DTO_ACTIVIDAD_DETALLE);

		setValue(0, grupoId);
		setValue(1, actividadId);
		setValue(2, estadoAsistente);
		setValue(3, asociadoId);
		setValue(4, nombreCompleto);
		setValue(5, tipo);
		setValue(6, ramaColonia);
		setValue(7, ramaManada);
		setValue(8, ramaExploradores);
		setValue(9, ramaExpedicion);
		setValue(10, ramaRuta);
		setValue(11, telefono);
	}
}
