/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.dd.tables.DtoCargoAsociado;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoCargoAsociadoRecord extends TableRecordImpl<DtoCargoAsociadoRecord> implements Record6<Integer, Integer, String, String, Boolean, Integer> {

	private static final long serialVersionUID = -241537499;

	/**
	 * Setter for <code>public.dto_cargo_asociado.asociado_id</code>.
	 */
	public void setAsociadoId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.dto_cargo_asociado.asociado_id</code>.
	 */
	public Integer getAsociadoId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.dto_cargo_asociado.id</code>.
	 */
	public void setId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.dto_cargo_asociado.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.dto_cargo_asociado.etiqueta</code>.
	 */
	public void setEtiqueta(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.dto_cargo_asociado.etiqueta</code>.
	 */
	public String getEtiqueta() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.dto_cargo_asociado.ambito</code>.
	 */
	public void setAmbito(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.dto_cargo_asociado.ambito</code>.
	 */
	public String getAmbito() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.dto_cargo_asociado.unico</code>.
	 */
	public void setUnico(Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.dto_cargo_asociado.unico</code>.
	 */
	public Boolean getUnico() {
		return (Boolean) getValue(4);
	}

	/**
	 * Setter for <code>public.dto_cargo_asociado.puntos</code>.
	 */
	public void setPuntos(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.dto_cargo_asociado.puntos</code>.
	 */
	public Integer getPuntos() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, String, String, Boolean, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, String, String, Boolean, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return DtoCargoAsociado.DTO_CARGO_ASOCIADO.ASOCIADO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return DtoCargoAsociado.DTO_CARGO_ASOCIADO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return DtoCargoAsociado.DTO_CARGO_ASOCIADO.ETIQUETA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return DtoCargoAsociado.DTO_CARGO_ASOCIADO.AMBITO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field5() {
		return DtoCargoAsociado.DTO_CARGO_ASOCIADO.UNICO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return DtoCargoAsociado.DTO_CARGO_ASOCIADO.PUNTOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getAsociadoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getEtiqueta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getAmbito();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value5() {
		return getUnico();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getPuntos();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoCargoAsociadoRecord value1(Integer value) {
		setAsociadoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoCargoAsociadoRecord value2(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoCargoAsociadoRecord value3(String value) {
		setEtiqueta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoCargoAsociadoRecord value4(String value) {
		setAmbito(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoCargoAsociadoRecord value5(Boolean value) {
		setUnico(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoCargoAsociadoRecord value6(Integer value) {
		setPuntos(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoCargoAsociadoRecord values(Integer value1, Integer value2, String value3, String value4, Boolean value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DtoCargoAsociadoRecord
	 */
	public DtoCargoAsociadoRecord() {
		super(DtoCargoAsociado.DTO_CARGO_ASOCIADO);
	}

	/**
	 * Create a detached, initialised DtoCargoAsociadoRecord
	 */
	public DtoCargoAsociadoRecord(Integer asociadoId, Integer id, String etiqueta, String ambito, Boolean unico, Integer puntos) {
		super(DtoCargoAsociado.DTO_CARGO_ASOCIADO);

		setValue(0, asociadoId);
		setValue(1, id);
		setValue(2, etiqueta);
		setValue(3, ambito);
		setValue(4, unico);
		setValue(5, puntos);
	}
}
