/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.dd.tables.DtoDatosGrupoRama;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoDatosGrupoRamaRecord extends TableRecordImpl<DtoDatosGrupoRamaRecord> implements Record6<String, Long, Long, Long, Long, Long> {

	private static final long serialVersionUID = 1252295377;

	/**
	 * Setter for <code>public.dto_datos_grupo_rama.grupo_id</code>.
	 */
	public void setGrupoId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.dto_datos_grupo_rama.grupo_id</code>.
	 */
	public String getGrupoId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.dto_datos_grupo_rama.colonia</code>.
	 */
	public void setColonia(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.dto_datos_grupo_rama.colonia</code>.
	 */
	public Long getColonia() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>public.dto_datos_grupo_rama.manada</code>.
	 */
	public void setManada(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.dto_datos_grupo_rama.manada</code>.
	 */
	public Long getManada() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>public.dto_datos_grupo_rama.exploradores</code>.
	 */
	public void setExploradores(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.dto_datos_grupo_rama.exploradores</code>.
	 */
	public Long getExploradores() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>public.dto_datos_grupo_rama.expedicion</code>.
	 */
	public void setExpedicion(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.dto_datos_grupo_rama.expedicion</code>.
	 */
	public Long getExpedicion() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>public.dto_datos_grupo_rama.ruta</code>.
	 */
	public void setRuta(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.dto_datos_grupo_rama.ruta</code>.
	 */
	public Long getRuta() {
		return (Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, Long, Long, Long, Long, Long> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<String, Long, Long, Long, Long, Long> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA.GRUPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA.COLONIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA.MANADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA.EXPLORADORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA.EXPEDICION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA.RUTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getGrupoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getColonia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getManada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getExploradores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getExpedicion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getRuta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRamaRecord value1(String value) {
		setGrupoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRamaRecord value2(Long value) {
		setColonia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRamaRecord value3(Long value) {
		setManada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRamaRecord value4(Long value) {
		setExploradores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRamaRecord value5(Long value) {
		setExpedicion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRamaRecord value6(Long value) {
		setRuta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRamaRecord values(String value1, Long value2, Long value3, Long value4, Long value5, Long value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DtoDatosGrupoRamaRecord
	 */
	public DtoDatosGrupoRamaRecord() {
		super(DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA);
	}

	/**
	 * Create a detached, initialised DtoDatosGrupoRamaRecord
	 */
	public DtoDatosGrupoRamaRecord(String grupoId, Long colonia, Long manada, Long exploradores, Long expedicion, Long ruta) {
		super(DtoDatosGrupoRama.DTO_DATOS_GRUPO_RAMA);

		setValue(0, grupoId);
		setValue(1, colonia);
		setValue(2, manada);
		setValue(3, exploradores);
		setValue(4, expedicion);
		setValue(5, ruta);
	}
}
