/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.dd.tables.LiquidacionCalculo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionCalculoRecord extends TableRecordImpl<LiquidacionCalculoRecord> implements Record7<String, Short, Integer, Long, Long, BigDecimal, Boolean> {

	private static final long serialVersionUID = 1264898943;

	/**
	 * Setter for <code>public.liquidacion_calculo.grupo_id</code>.
	 */
	public void setGrupoId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.liquidacion_calculo.grupo_id</code>.
	 */
	public String getGrupoId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.liquidacion_calculo.ronda_id</code>.
	 */
	public void setRondaId(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.liquidacion_calculo.ronda_id</code>.
	 */
	public Short getRondaId() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>public.liquidacion_calculo.liquidacion_id</code>.
	 */
	public void setLiquidacionId(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.liquidacion_calculo.liquidacion_id</code>.
	 */
	public Integer getLiquidacionId() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.liquidacion_calculo.activos</code>.
	 */
	public void setActivos(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.liquidacion_calculo.activos</code>.
	 */
	public Long getActivos() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>public.liquidacion_calculo.diferencia</code>.
	 */
	public void setDiferencia(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.liquidacion_calculo.diferencia</code>.
	 */
	public Long getDiferencia() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>public.liquidacion_calculo.subtotal</code>.
	 */
	public void setSubtotal(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.liquidacion_calculo.subtotal</code>.
	 */
	public BigDecimal getSubtotal() {
		return (BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>public.liquidacion_calculo.borrador</code>.
	 */
	public void setBorrador(Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.liquidacion_calculo.borrador</code>.
	 */
	public Boolean getBorrador() {
		return (Boolean) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, Short, Integer, Long, Long, BigDecimal, Boolean> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, Short, Integer, Long, Long, BigDecimal, Boolean> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return LiquidacionCalculo.LIQUIDACION_CALCULO.GRUPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return LiquidacionCalculo.LIQUIDACION_CALCULO.RONDA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return LiquidacionCalculo.LIQUIDACION_CALCULO.LIQUIDACION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return LiquidacionCalculo.LIQUIDACION_CALCULO.ACTIVOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return LiquidacionCalculo.LIQUIDACION_CALCULO.DIFERENCIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return LiquidacionCalculo.LIQUIDACION_CALCULO.SUBTOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field7() {
		return LiquidacionCalculo.LIQUIDACION_CALCULO.BORRADOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getGrupoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getRondaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getLiquidacionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getActivos();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getDiferencia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getSubtotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value7() {
		return getBorrador();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord value1(String value) {
		setGrupoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord value2(Short value) {
		setRondaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord value3(Integer value) {
		setLiquidacionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord value4(Long value) {
		setActivos(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord value5(Long value) {
		setDiferencia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord value6(BigDecimal value) {
		setSubtotal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord value7(Boolean value) {
		setBorrador(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculoRecord values(String value1, Short value2, Integer value3, Long value4, Long value5, BigDecimal value6, Boolean value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LiquidacionCalculoRecord
	 */
	public LiquidacionCalculoRecord() {
		super(LiquidacionCalculo.LIQUIDACION_CALCULO);
	}

	/**
	 * Create a detached, initialised LiquidacionCalculoRecord
	 */
	public LiquidacionCalculoRecord(String grupoId, Short rondaId, Integer liquidacionId, Long activos, Long diferencia, BigDecimal subtotal, Boolean borrador) {
		super(LiquidacionCalculo.LIQUIDACION_CALCULO);

		setValue(0, grupoId);
		setValue(1, rondaId);
		setValue(2, liquidacionId);
		setValue(3, activos);
		setValue(4, diferencia);
		setValue(5, subtotal);
		setValue(6, borrador);
	}
}
