/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsistenteActividad implements Serializable {

	private static final long serialVersionUID = 1159986275;

	private final Integer actividadId;
	private final Integer asociadoId;
	private final String  estado;

	public AsistenteActividad(AsistenteActividad value) {
		this.actividadId = value.actividadId;
		this.asociadoId = value.asociadoId;
		this.estado = value.estado;
	}

	public AsistenteActividad(
		Integer actividadId,
		Integer asociadoId,
		String  estado
	) {
		this.actividadId = actividadId;
		this.asociadoId = asociadoId;
		this.estado = estado;
	}

	public Integer getActividadId() {
		return this.actividadId;
	}

	public Integer getAsociadoId() {
		return this.asociadoId;
	}

	public String getEstado() {
		return this.estado;
	}
}
