/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoActividadDetalle implements Serializable {

	private static final long serialVersionUID = 1487134532;

	private final String  grupoId;
	private final Integer actividadId;
	private final String  estadoAsistente;
	private final Integer asociadoId;
	private final String  nombreCompleto;
	private final String  tipo;
	private final Boolean ramaColonia;
	private final Boolean ramaManada;
	private final Boolean ramaExploradores;
	private final Boolean ramaExpedicion;
	private final Boolean ramaRuta;
	private final String  telefono;

	public DtoActividadDetalle(DtoActividadDetalle value) {
		this.grupoId = value.grupoId;
		this.actividadId = value.actividadId;
		this.estadoAsistente = value.estadoAsistente;
		this.asociadoId = value.asociadoId;
		this.nombreCompleto = value.nombreCompleto;
		this.tipo = value.tipo;
		this.ramaColonia = value.ramaColonia;
		this.ramaManada = value.ramaManada;
		this.ramaExploradores = value.ramaExploradores;
		this.ramaExpedicion = value.ramaExpedicion;
		this.ramaRuta = value.ramaRuta;
		this.telefono = value.telefono;
	}

	public DtoActividadDetalle(
		String  grupoId,
		Integer actividadId,
		String  estadoAsistente,
		Integer asociadoId,
		String  nombreCompleto,
		String  tipo,
		Boolean ramaColonia,
		Boolean ramaManada,
		Boolean ramaExploradores,
		Boolean ramaExpedicion,
		Boolean ramaRuta,
		String  telefono
	) {
		this.grupoId = grupoId;
		this.actividadId = actividadId;
		this.estadoAsistente = estadoAsistente;
		this.asociadoId = asociadoId;
		this.nombreCompleto = nombreCompleto;
		this.tipo = tipo;
		this.ramaColonia = ramaColonia;
		this.ramaManada = ramaManada;
		this.ramaExploradores = ramaExploradores;
		this.ramaExpedicion = ramaExpedicion;
		this.ramaRuta = ramaRuta;
		this.telefono = telefono;
	}

	public String getGrupoId() {
		return this.grupoId;
	}

	public Integer getActividadId() {
		return this.actividadId;
	}

	public String getEstadoAsistente() {
		return this.estadoAsistente;
	}

	public Integer getAsociadoId() {
		return this.asociadoId;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public String getTipo() {
		return this.tipo;
	}

	public Boolean getRamaColonia() {
		return this.ramaColonia;
	}

	public Boolean getRamaManada() {
		return this.ramaManada;
	}

	public Boolean getRamaExploradores() {
		return this.ramaExploradores;
	}

	public Boolean getRamaExpedicion() {
		return this.ramaExpedicion;
	}

	public Boolean getRamaRuta() {
		return this.ramaRuta;
	}

	public String getTelefono() {
		return this.telefono;
	}
}
