/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoCargoAsociado implements Serializable {

	private static final long serialVersionUID = 808088407;

	private final Integer asociadoId;
	private final Integer id;
	private final String  etiqueta;
	private final String  ambito;
	private final Boolean unico;
	private final Integer puntos;

	public DtoCargoAsociado(DtoCargoAsociado value) {
		this.asociadoId = value.asociadoId;
		this.id = value.id;
		this.etiqueta = value.etiqueta;
		this.ambito = value.ambito;
		this.unico = value.unico;
		this.puntos = value.puntos;
	}

	public DtoCargoAsociado(
		Integer asociadoId,
		Integer id,
		String  etiqueta,
		String  ambito,
		Boolean unico,
		Integer puntos
	) {
		this.asociadoId = asociadoId;
		this.id = id;
		this.etiqueta = etiqueta;
		this.ambito = ambito;
		this.unico = unico;
		this.puntos = puntos;
	}

	public Integer getAsociadoId() {
		return this.asociadoId;
	}

	public Integer getId() {
		return this.id;
	}

	public String getEtiqueta() {
		return this.etiqueta;
	}

	public String getAmbito() {
		return this.ambito;
	}

	public Boolean getUnico() {
		return this.unico;
	}

	public Integer getPuntos() {
		return this.puntos;
	}
}
