/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoDatosGrupoTipo implements Serializable {

	private static final long serialVersionUID = 1886560494;

	private final String grupoId;
	private final Long   joven;
	private final Long   kraal;
	private final Long   comite;

	public DtoDatosGrupoTipo(DtoDatosGrupoTipo value) {
		this.grupoId = value.grupoId;
		this.joven = value.joven;
		this.kraal = value.kraal;
		this.comite = value.comite;
	}

	public DtoDatosGrupoTipo(
		String grupoId,
		Long   joven,
		Long   kraal,
		Long   comite
	) {
		this.grupoId = grupoId;
		this.joven = joven;
		this.kraal = kraal;
		this.comite = comite;
	}

	public String getGrupoId() {
		return this.grupoId;
	}

	public Long getJoven() {
		return this.joven;
	}

	public Long getKraal() {
		return this.kraal;
	}

	public Long getComite() {
		return this.comite;
	}
}
