/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoDatosPeriodoTipo implements Serializable {

	private static final long serialVersionUID = 930654021;

	private final Integer periodo;
	private final Long    jovenes;
	private final Long    voluntarios;
	private final Long    total;

	public DtoDatosPeriodoTipo(DtoDatosPeriodoTipo value) {
		this.periodo = value.periodo;
		this.jovenes = value.jovenes;
		this.voluntarios = value.voluntarios;
		this.total = value.total;
	}

	public DtoDatosPeriodoTipo(
		Integer periodo,
		Long    jovenes,
		Long    voluntarios,
		Long    total
	) {
		this.periodo = periodo;
		this.jovenes = jovenes;
		this.voluntarios = voluntarios;
		this.total = total;
	}

	public Integer getPeriodo() {
		return this.periodo;
	}

	public Long getJovenes() {
		return this.jovenes;
	}

	public Long getVoluntarios() {
		return this.voluntarios;
	}

	public Long getTotal() {
		return this.total;
	}
}
