/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoMiembrosEscuela implements Serializable {

	private static final long serialVersionUID = 1771765799;

	private final Integer id;
	private final Integer cargoId;
	private final String  nombreCompleto;
	private final String  nombreGrupo;
	private final String  etiqueta;
	private final Boolean mesaPedagogica;
	private final String  telefono;
	private final String  email;
	private final Date    fechaNacimiento;

	public DtoMiembrosEscuela(DtoMiembrosEscuela value) {
		this.id = value.id;
		this.cargoId = value.cargoId;
		this.nombreCompleto = value.nombreCompleto;
		this.nombreGrupo = value.nombreGrupo;
		this.etiqueta = value.etiqueta;
		this.mesaPedagogica = value.mesaPedagogica;
		this.telefono = value.telefono;
		this.email = value.email;
		this.fechaNacimiento = value.fechaNacimiento;
	}

	public DtoMiembrosEscuela(
		Integer id,
		Integer cargoId,
		String  nombreCompleto,
		String  nombreGrupo,
		String  etiqueta,
		Boolean mesaPedagogica,
		String  telefono,
		String  email,
		Date    fechaNacimiento
	) {
		this.id = id;
		this.cargoId = cargoId;
		this.nombreCompleto = nombreCompleto;
		this.nombreGrupo = nombreGrupo;
		this.etiqueta = etiqueta;
		this.mesaPedagogica = mesaPedagogica;
		this.telefono = telefono;
		this.email = email;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Integer getId() {
		return this.id;
	}

	public Integer getCargoId() {
		return this.cargoId;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public String getNombreGrupo() {
		return this.nombreGrupo;
	}

	public String getEtiqueta() {
		return this.etiqueta;
	}

	public Boolean getMesaPedagogica() {
		return this.mesaPedagogica;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}
}
