/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Grupo implements Serializable {

	private static final long serialVersionUID = -375160192;

	private final String  id;
	private final String  nombre;
	private final Integer codigoPostal;
	private final String  municipio;
	private final Date    aniversario;
	private final String  telefono1;
	private final String  telefono2;
	private final String  email;
	private final String  web;
	private final String  entidadPatrocinadora;
	private final Integer asociacion;
	private final String  direccion;

	public Grupo(Grupo value) {
		this.id = value.id;
		this.nombre = value.nombre;
		this.codigoPostal = value.codigoPostal;
		this.municipio = value.municipio;
		this.aniversario = value.aniversario;
		this.telefono1 = value.telefono1;
		this.telefono2 = value.telefono2;
		this.email = value.email;
		this.web = value.web;
		this.entidadPatrocinadora = value.entidadPatrocinadora;
		this.asociacion = value.asociacion;
		this.direccion = value.direccion;
	}

	public Grupo(
		String  id,
		String  nombre,
		Integer codigoPostal,
		String  municipio,
		Date    aniversario,
		String  telefono1,
		String  telefono2,
		String  email,
		String  web,
		String  entidadPatrocinadora,
		Integer asociacion,
		String  direccion
	) {
		this.id = id;
		this.nombre = nombre;
		this.codigoPostal = codigoPostal;
		this.municipio = municipio;
		this.aniversario = aniversario;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
		this.email = email;
		this.web = web;
		this.entidadPatrocinadora = entidadPatrocinadora;
		this.asociacion = asociacion;
		this.direccion = direccion;
	}

	public String getId() {
		return this.id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public Integer getCodigoPostal() {
		return this.codigoPostal;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public Date getAniversario() {
		return this.aniversario;
	}

	public String getTelefono1() {
		return this.telefono1;
	}

	public String getTelefono2() {
		return this.telefono2;
	}

	public String getEmail() {
		return this.email;
	}

	public String getWeb() {
		return this.web;
	}

	public String getEntidadPatrocinadora() {
		return this.entidadPatrocinadora;
	}

	public Integer getAsociacion() {
		return this.asociacion;
	}

	public String getDireccion() {
		return this.direccion;
	}
}
