/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionAsociado implements Serializable {

	private static final long serialVersionUID = 930942704;

	private final Integer   liquidacionId;
	private final Integer   asociadoId;
	private final String    tipo;
	private final String    nombre;
	private final String    apellidos;
	private final Timestamp fechaAlta;
	private final Timestamp fechaActualizacion;
	private final Boolean   ramaColonia;
	private final Boolean   ramaManada;
	private final Boolean   ramaExploradores;
	private final Boolean   ramaExpedicion;
	private final Boolean   ramaRuta;

	public LiquidacionAsociado(LiquidacionAsociado value) {
		this.liquidacionId = value.liquidacionId;
		this.asociadoId = value.asociadoId;
		this.tipo = value.tipo;
		this.nombre = value.nombre;
		this.apellidos = value.apellidos;
		this.fechaAlta = value.fechaAlta;
		this.fechaActualizacion = value.fechaActualizacion;
		this.ramaColonia = value.ramaColonia;
		this.ramaManada = value.ramaManada;
		this.ramaExploradores = value.ramaExploradores;
		this.ramaExpedicion = value.ramaExpedicion;
		this.ramaRuta = value.ramaRuta;
	}

	public LiquidacionAsociado(
		Integer   liquidacionId,
		Integer   asociadoId,
		String    tipo,
		String    nombre,
		String    apellidos,
		Timestamp fechaAlta,
		Timestamp fechaActualizacion,
		Boolean   ramaColonia,
		Boolean   ramaManada,
		Boolean   ramaExploradores,
		Boolean   ramaExpedicion,
		Boolean   ramaRuta
	) {
		this.liquidacionId = liquidacionId;
		this.asociadoId = asociadoId;
		this.tipo = tipo;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaAlta = fechaAlta;
		this.fechaActualizacion = fechaActualizacion;
		this.ramaColonia = ramaColonia;
		this.ramaManada = ramaManada;
		this.ramaExploradores = ramaExploradores;
		this.ramaExpedicion = ramaExpedicion;
		this.ramaRuta = ramaRuta;
	}

	public Integer getLiquidacionId() {
		return this.liquidacionId;
	}

	public Integer getAsociadoId() {
		return this.asociadoId;
	}

	public String getTipo() {
		return this.tipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public Timestamp getFechaAlta() {
		return this.fechaAlta;
	}

	public Timestamp getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public Boolean getRamaColonia() {
		return this.ramaColonia;
	}

	public Boolean getRamaManada() {
		return this.ramaManada;
	}

	public Boolean getRamaExploradores() {
		return this.ramaExploradores;
	}

	public Boolean getRamaExpedicion() {
		return this.ramaExpedicion;
	}

	public Boolean getRamaRuta() {
		return this.ramaRuta;
	}
}
