/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;
import org.scoutsfev.cudu.db.routines.Edad;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

	/**
	 * Call <code>public.edad</code>
	 */
	public static Double edad(Configuration configuration, Date __1) {
		Edad f = new Edad();
		f.set__1(__1);

		f.execute(configuration);
		return f.getReturnValue();
	}

	/**
	 * Get <code>public.edad</code> as a field
	 */
	public static Field<Double> edad(Date __1) {
		Edad f = new Edad();
		f.set__1(__1);

		return f.asField();
	}

	/**
	 * Get <code>public.edad</code> as a field
	 */
	public static Field<Double> edad(Field<Date> __1) {
		Edad f = new Edad();
		f.set__1(__1);

		return f.asField();
	}
}
