/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.routines;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.scoutsfev.cudu.dd.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrearLiquidacion extends AbstractRoutine<Integer> {

	private static final long serialVersionUID = 2057887357;

	/**
	 * The parameter <code>public.crear_liquidacion.RETURN_VALUE</code>.
	 */
	public static final Parameter<Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false);

	/**
	 * The parameter <code>public.crear_liquidacion.grupo_id</code>.
	 */
	public static final Parameter<String> GRUPO_ID = createParameter("grupo_id", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * The parameter <code>public.crear_liquidacion.ronda_id</code>.
	 */
	public static final Parameter<Short> RONDA_ID = createParameter("ronda_id", org.jooq.impl.SQLDataType.SMALLINT, false);

	/**
	 * The parameter <code>public.crear_liquidacion.creado_por</code>.
	 */
	public static final Parameter<String> CREADO_POR = createParameter("creado_por", org.jooq.impl.SQLDataType.VARCHAR, false);

	/**
	 * Create a new routine call instance
	 */
	public CrearLiquidacion() {
		super("crear_liquidacion", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER);

		setReturnParameter(RETURN_VALUE);
		addInParameter(GRUPO_ID);
		addInParameter(RONDA_ID);
		addInParameter(CREADO_POR);
	}

	/**
	 * Set the <code>grupo_id</code> parameter IN value to the routine
	 */
	public void setGrupoId(String value) {
		setValue(GRUPO_ID, value);
	}

	/**
	 * Set the <code>grupo_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setGrupoId(Field<String> field) {
		setField(GRUPO_ID, field);
	}

	/**
	 * Set the <code>ronda_id</code> parameter IN value to the routine
	 */
	public void setRondaId(Short value) {
		setValue(RONDA_ID, value);
	}

	/**
	 * Set the <code>ronda_id</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setRondaId(Field<Short> field) {
		setField(RONDA_ID, field);
	}

	/**
	 * Set the <code>creado_por</code> parameter IN value to the routine
	 */
	public void setCreadoPor(String value) {
		setValue(CREADO_POR, value);
	}

	/**
	 * Set the <code>creado_por</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void setCreadoPor(Field<String> field) {
		setField(CREADO_POR, field);
	}
}
