/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.routines;


import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.scoutsfev.cudu.dd.Public;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NuevaFechaActualizacion extends AbstractRoutine<Object> {

	private static final long serialVersionUID = -997672576;

	/**
	 * The parameter <code>public.nueva_fecha_actualizacion.RETURN_VALUE</code>.
	 */
	public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"), false);

	/**
	 * Create a new routine call instance
	 */
	public NuevaFechaActualizacion() {
		super("nueva_fecha_actualizacion", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("trigger"));

		setReturnParameter(RETURN_VALUE);
	}
}
