/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.scoutsfev.cudu.db.tables.Actividad;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActividadRecord extends UpdatableRecordImpl<ActividadRecord> implements Record17<Integer, String, String, Date, Date, String, String, String, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Timestamp, Timestamp> {

	private static final long serialVersionUID = -2102571845;

	/**
	 * Setter for <code>public.actividad.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.actividad.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.actividad.grupo_id</code>.
	 */
	public void setGrupoId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.actividad.grupo_id</code>.
	 */
	public String getGrupoId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.actividad.nombre</code>.
	 */
	public void setNombre(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.actividad.nombre</code>.
	 */
	public String getNombre() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.actividad.fecha_inicio</code>.
	 */
	public void setFechaInicio(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.actividad.fecha_inicio</code>.
	 */
	public Date getFechaInicio() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>public.actividad.fecha_fin</code>.
	 */
	public void setFechaFin(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.actividad.fecha_fin</code>.
	 */
	public Date getFechaFin() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>public.actividad.creada_por</code>.
	 */
	public void setCreadaPor(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.actividad.creada_por</code>.
	 */
	public String getCreadaPor() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.actividad.lugar</code>.
	 */
	public void setLugar(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.actividad.lugar</code>.
	 */
	public String getLugar() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.actividad.precio</code>.
	 */
	public void setPrecio(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.actividad.precio</code>.
	 */
	public String getPrecio() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.actividad.responsable</code>.
	 */
	public void setResponsable(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.actividad.responsable</code>.
	 */
	public String getResponsable() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.actividad.notas</code>.
	 */
	public void setNotas(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.actividad.notas</code>.
	 */
	public String getNotas() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>public.actividad.rama_colonia</code>.
	 */
	public void setRamaColonia(Boolean value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.actividad.rama_colonia</code>.
	 */
	public Boolean getRamaColonia() {
		return (Boolean) getValue(10);
	}

	/**
	 * Setter for <code>public.actividad.rama_expedicion</code>.
	 */
	public void setRamaExpedicion(Boolean value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.actividad.rama_expedicion</code>.
	 */
	public Boolean getRamaExpedicion() {
		return (Boolean) getValue(11);
	}

	/**
	 * Setter for <code>public.actividad.rama_exploradores</code>.
	 */
	public void setRamaExploradores(Boolean value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.actividad.rama_exploradores</code>.
	 */
	public Boolean getRamaExploradores() {
		return (Boolean) getValue(12);
	}

	/**
	 * Setter for <code>public.actividad.rama_manada</code>.
	 */
	public void setRamaManada(Boolean value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>public.actividad.rama_manada</code>.
	 */
	public Boolean getRamaManada() {
		return (Boolean) getValue(13);
	}

	/**
	 * Setter for <code>public.actividad.rama_ruta</code>.
	 */
	public void setRamaRuta(Boolean value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>public.actividad.rama_ruta</code>.
	 */
	public Boolean getRamaRuta() {
		return (Boolean) getValue(14);
	}

	/**
	 * Setter for <code>public.actividad.fecha_creacion</code>.
	 */
	public void setFechaCreacion(Timestamp value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>public.actividad.fecha_creacion</code>.
	 */
	public Timestamp getFechaCreacion() {
		return (Timestamp) getValue(15);
	}

	/**
	 * Setter for <code>public.actividad.fecha_baja</code>.
	 */
	public void setFechaBaja(Timestamp value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>public.actividad.fecha_baja</code>.
	 */
	public Timestamp getFechaBaja() {
		return (Timestamp) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<Integer, String, String, Date, Date, String, String, String, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Timestamp, Timestamp> fieldsRow() {
		return (Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row17<Integer, String, String, Date, Date, String, String, String, String, String, Boolean, Boolean, Boolean, Boolean, Boolean, Timestamp, Timestamp> valuesRow() {
		return (Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Actividad.ACTIVIDAD.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Actividad.ACTIVIDAD.GRUPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Actividad.ACTIVIDAD.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return Actividad.ACTIVIDAD.FECHA_INICIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return Actividad.ACTIVIDAD.FECHA_FIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Actividad.ACTIVIDAD.CREADA_POR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Actividad.ACTIVIDAD.LUGAR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return Actividad.ACTIVIDAD.PRECIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return Actividad.ACTIVIDAD.RESPONSABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return Actividad.ACTIVIDAD.NOTAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field11() {
		return Actividad.ACTIVIDAD.RAMA_COLONIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field12() {
		return Actividad.ACTIVIDAD.RAMA_EXPEDICION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field13() {
		return Actividad.ACTIVIDAD.RAMA_EXPLORADORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field14() {
		return Actividad.ACTIVIDAD.RAMA_MANADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field15() {
		return Actividad.ACTIVIDAD.RAMA_RUTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field16() {
		return Actividad.ACTIVIDAD.FECHA_CREACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field17() {
		return Actividad.ACTIVIDAD.FECHA_BAJA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getGrupoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getFechaInicio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getFechaFin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getCreadaPor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getLugar();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getPrecio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getResponsable();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getNotas();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value11() {
		return getRamaColonia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value12() {
		return getRamaExpedicion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value13() {
		return getRamaExploradores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value14() {
		return getRamaManada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value15() {
		return getRamaRuta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value16() {
		return getFechaCreacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value17() {
		return getFechaBaja();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value2(String value) {
		setGrupoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value3(String value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value4(Date value) {
		setFechaInicio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value5(Date value) {
		setFechaFin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value6(String value) {
		setCreadaPor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value7(String value) {
		setLugar(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value8(String value) {
		setPrecio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value9(String value) {
		setResponsable(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value10(String value) {
		setNotas(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value11(Boolean value) {
		setRamaColonia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value12(Boolean value) {
		setRamaExpedicion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value13(Boolean value) {
		setRamaExploradores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value14(Boolean value) {
		setRamaManada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value15(Boolean value) {
		setRamaRuta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value16(Timestamp value) {
		setFechaCreacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord value17(Timestamp value) {
		setFechaBaja(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ActividadRecord values(Integer value1, String value2, String value3, Date value4, Date value5, String value6, String value7, String value8, String value9, String value10, Boolean value11, Boolean value12, Boolean value13, Boolean value14, Boolean value15, Timestamp value16, Timestamp value17) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		value15(value15);
		value16(value16);
		value17(value17);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ActividadRecord
	 */
	public ActividadRecord() {
		super(Actividad.ACTIVIDAD);
	}

	/**
	 * Create a detached, initialised ActividadRecord
	 */
	public ActividadRecord(Integer id, String grupoId, String nombre, Date fechaInicio, Date fechaFin, String creadaPor, String lugar, String precio, String responsable, String notas, Boolean ramaColonia, Boolean ramaExpedicion, Boolean ramaExploradores, Boolean ramaManada, Boolean ramaRuta, Timestamp fechaCreacion, Timestamp fechaBaja) {
		super(Actividad.ACTIVIDAD);

		setValue(0, id);
		setValue(1, grupoId);
		setValue(2, nombre);
		setValue(3, fechaInicio);
		setValue(4, fechaFin);
		setValue(5, creadaPor);
		setValue(6, lugar);
		setValue(7, precio);
		setValue(8, responsable);
		setValue(9, notas);
		setValue(10, ramaColonia);
		setValue(11, ramaExpedicion);
		setValue(12, ramaExploradores);
		setValue(13, ramaManada);
		setValue(14, ramaRuta);
		setValue(15, fechaCreacion);
		setValue(16, fechaBaja);
	}
}
