/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.scoutsfev.cudu.db.tables.AsistenteActividad;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AsistenteActividadRecord extends UpdatableRecordImpl<AsistenteActividadRecord> implements Record3<Integer, Integer, String> {

	private static final long serialVersionUID = 2067685285;

	/**
	 * Setter for <code>public.asistente_actividad.actividad_id</code>.
	 */
	public void setActividadId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.asistente_actividad.actividad_id</code>.
	 */
	public Integer getActividadId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.asistente_actividad.asociado_id</code>.
	 */
	public void setAsociadoId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.asistente_actividad.asociado_id</code>.
	 */
	public Integer getAsociadoId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.asistente_actividad.estado</code>.
	 */
	public void setEstado(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.asistente_actividad.estado</code>.
	 */
	public String getEstado() {
		return (String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Integer, Integer, String> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AsistenteActividad.ASISTENTE_ACTIVIDAD.ACTIVIDAD_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AsistenteActividad.ASISTENTE_ACTIVIDAD.ASOCIADO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AsistenteActividad.ASISTENTE_ACTIVIDAD.ESTADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getActividadId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getAsociadoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getEstado();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsistenteActividadRecord value1(Integer value) {
		setActividadId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsistenteActividadRecord value2(Integer value) {
		setAsociadoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsistenteActividadRecord value3(String value) {
		setEstado(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AsistenteActividadRecord values(Integer value1, Integer value2, String value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AsistenteActividadRecord
	 */
	public AsistenteActividadRecord() {
		super(AsistenteActividad.ASISTENTE_ACTIVIDAD);
	}

	/**
	 * Create a detached, initialised AsistenteActividadRecord
	 */
	public AsistenteActividadRecord(Integer actividadId, Integer asociadoId, String estado) {
		super(AsistenteActividad.ASISTENTE_ACTIVIDAD);

		setValue(0, actividadId);
		setValue(1, asociadoId);
		setValue(2, estado);
	}
}
