/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.scoutsfev.cudu.db.tables.CursoFormador;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CursoFormadorRecord extends UpdatableRecordImpl<CursoFormadorRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 1800966370;

	/**
	 * Setter for <code>public.curso_formador.curso_id</code>.
	 */
	public void setCursoId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.curso_formador.curso_id</code>.
	 */
	public Integer getCursoId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.curso_formador.asociado_id</code>.
	 */
	public void setAsociadoId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.curso_formador.asociado_id</code>.
	 */
	public Integer getAsociadoId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CursoFormador.CURSO_FORMADOR.CURSO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CursoFormador.CURSO_FORMADOR.ASOCIADO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getCursoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getAsociadoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoFormadorRecord value1(Integer value) {
		setCursoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoFormadorRecord value2(Integer value) {
		setAsociadoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoFormadorRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CursoFormadorRecord
	 */
	public CursoFormadorRecord() {
		super(CursoFormador.CURSO_FORMADOR);
	}

	/**
	 * Create a detached, initialised CursoFormadorRecord
	 */
	public CursoFormadorRecord(Integer cursoId, Integer asociadoId) {
		super(CursoFormador.CURSO_FORMADOR);

		setValue(0, cursoId);
		setValue(1, asociadoId);
	}
}
