/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.scoutsfev.cudu.db.tables.CursoParticipante;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CursoParticipanteRecord extends UpdatableRecordImpl<CursoParticipanteRecord> implements Record4<Integer, Integer, Integer, Timestamp> {

	private static final long serialVersionUID = 483322936;

	/**
	 * Setter for <code>public.curso_participante.curso_id</code>.
	 */
	public void setCursoId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.curso_participante.curso_id</code>.
	 */
	public Integer getCursoId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.curso_participante.asociado_id</code>.
	 */
	public void setAsociadoId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.curso_participante.asociado_id</code>.
	 */
	public Integer getAsociadoId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.curso_participante.secuencia_inscripcion</code>.
	 */
	public void setSecuenciaInscripcion(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.curso_participante.secuencia_inscripcion</code>.
	 */
	public Integer getSecuenciaInscripcion() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.curso_participante.fecha_inscripcion</code>.
	 */
	public void setFechaInscripcion(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.curso_participante.fecha_inscripcion</code>.
	 */
	public Timestamp getFechaInscripcion() {
		return (Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Timestamp> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, Integer, Timestamp> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CursoParticipante.CURSO_PARTICIPANTE.CURSO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CursoParticipante.CURSO_PARTICIPANTE.ASOCIADO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return CursoParticipante.CURSO_PARTICIPANTE.SECUENCIA_INSCRIPCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return CursoParticipante.CURSO_PARTICIPANTE.FECHA_INSCRIPCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getCursoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getAsociadoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getSecuenciaInscripcion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getFechaInscripcion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoParticipanteRecord value1(Integer value) {
		setCursoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoParticipanteRecord value2(Integer value) {
		setAsociadoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoParticipanteRecord value3(Integer value) {
		setSecuenciaInscripcion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoParticipanteRecord value4(Timestamp value) {
		setFechaInscripcion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CursoParticipanteRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CursoParticipanteRecord
	 */
	public CursoParticipanteRecord() {
		super(CursoParticipante.CURSO_PARTICIPANTE);
	}

	/**
	 * Create a detached, initialised CursoParticipanteRecord
	 */
	public CursoParticipanteRecord(Integer cursoId, Integer asociadoId, Integer secuenciaInscripcion, Timestamp fechaInscripcion) {
		super(CursoParticipante.CURSO_PARTICIPANTE);

		setValue(0, cursoId);
		setValue(1, asociadoId);
		setValue(2, secuenciaInscripcion);
		setValue(3, fechaInscripcion);
	}
}
