/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.db.tables.DtoDatosRamaTipo;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoDatosRamaTipoRecord extends TableRecordImpl<DtoDatosRamaTipoRecord> implements Record7<Boolean, Long, Long, Long, Long, Long, Long> {

	private static final long serialVersionUID = 1306875969;

	/**
	 * Setter for <code>public.dto_datos_rama_tipo.es_joven</code>.
	 */
	public void setEsJoven(Boolean value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.dto_datos_rama_tipo.es_joven</code>.
	 */
	public Boolean getEsJoven() {
		return (Boolean) getValue(0);
	}

	/**
	 * Setter for <code>public.dto_datos_rama_tipo.colonia</code>.
	 */
	public void setColonia(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.dto_datos_rama_tipo.colonia</code>.
	 */
	public Long getColonia() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>public.dto_datos_rama_tipo.manada</code>.
	 */
	public void setManada(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.dto_datos_rama_tipo.manada</code>.
	 */
	public Long getManada() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>public.dto_datos_rama_tipo.exploradores</code>.
	 */
	public void setExploradores(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.dto_datos_rama_tipo.exploradores</code>.
	 */
	public Long getExploradores() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>public.dto_datos_rama_tipo.expedicion</code>.
	 */
	public void setExpedicion(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.dto_datos_rama_tipo.expedicion</code>.
	 */
	public Long getExpedicion() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>public.dto_datos_rama_tipo.ruta</code>.
	 */
	public void setRuta(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.dto_datos_rama_tipo.ruta</code>.
	 */
	public Long getRuta() {
		return (Long) getValue(5);
	}

	/**
	 * Setter for <code>public.dto_datos_rama_tipo.total</code>.
	 */
	public void setTotal(Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.dto_datos_rama_tipo.total</code>.
	 */
	public Long getTotal() {
		return (Long) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Boolean, Long, Long, Long, Long, Long, Long> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Boolean, Long, Long, Long, Long, Long, Long> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Boolean> field1() {
		return DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO.ES_JOVEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO.COLONIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO.MANADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO.EXPLORADORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO.EXPEDICION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO.RUTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field7() {
		return DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO.TOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Boolean value1() {
		return getEsJoven();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getColonia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getManada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getExploradores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getExpedicion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getRuta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value7() {
		return getTotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord value1(Boolean value) {
		setEsJoven(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord value2(Long value) {
		setColonia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord value3(Long value) {
		setManada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord value4(Long value) {
		setExploradores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord value5(Long value) {
		setExpedicion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord value6(Long value) {
		setRuta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord value7(Long value) {
		setTotal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosRamaTipoRecord values(Boolean value1, Long value2, Long value3, Long value4, Long value5, Long value6, Long value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DtoDatosRamaTipoRecord
	 */
	public DtoDatosRamaTipoRecord() {
		super(DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO);
	}

	/**
	 * Create a detached, initialised DtoDatosRamaTipoRecord
	 */
	public DtoDatosRamaTipoRecord(Boolean esJoven, Long colonia, Long manada, Long exploradores, Long expedicion, Long ruta, Long total) {
		super(DtoDatosRamaTipo.DTO_DATOS_RAMA_TIPO);

		setValue(0, esJoven);
		setValue(1, colonia);
		setValue(2, manada);
		setValue(3, exploradores);
		setValue(4, expedicion);
		setValue(5, ruta);
		setValue(6, total);
	}
}
