/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.db.tables.DtoMiembrosCurso;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoMiembrosCursoRecord extends TableRecordImpl<DtoMiembrosCursoRecord> implements Record10<Integer, Integer, String, Integer, String, String, String, String, String, Date> {

	private static final long serialVersionUID = 467048656;

	/**
	 * Setter for <code>public.dto_miembros_curso.curso_id</code>.
	 */
	public void setCursoId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.curso_id</code>.
	 */
	public Integer getCursoId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.id</code>.
	 */
	public void setId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.tipo_miembro</code>.
	 */
	public void setTipoMiembro(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.tipo_miembro</code>.
	 */
	public String getTipoMiembro() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.secuencia_inscripcion</code>.
	 */
	public void setSecuenciaInscripcion(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.secuencia_inscripcion</code>.
	 */
	public Integer getSecuenciaInscripcion() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.tipo</code>.
	 */
	public void setTipo(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.tipo</code>.
	 */
	public String getTipo() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.nombre_completo</code>.
	 */
	public void setNombreCompleto(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.nombre_completo</code>.
	 */
	public String getNombreCompleto() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.nombre_grupo</code>.
	 */
	public void setNombreGrupo(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.nombre_grupo</code>.
	 */
	public String getNombreGrupo() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.telefono</code>.
	 */
	public void setTelefono(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.telefono</code>.
	 */
	public String getTelefono() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.email</code>.
	 */
	public void setEmail(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.email</code>.
	 */
	public String getEmail() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>public.dto_miembros_curso.fecha_nacimiento</code>.
	 */
	public void setFechaNacimiento(Date value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.dto_miembros_curso.fecha_nacimiento</code>.
	 */
	public Date getFechaNacimiento() {
		return (Date) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, String, Integer, String, String, String, String, String, Date> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Integer, String, Integer, String, String, String, String, String, Date> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.CURSO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.TIPO_MIEMBRO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.SECUENCIA_INSCRIPCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.TIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.NOMBRE_COMPLETO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.NOMBRE_GRUPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.TELEFONO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field10() {
		return DtoMiembrosCurso.DTO_MIEMBROS_CURSO.FECHA_NACIMIENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getCursoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTipoMiembro();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getSecuenciaInscripcion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getNombreCompleto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getNombreGrupo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getTelefono();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value10() {
		return getFechaNacimiento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value1(Integer value) {
		setCursoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value2(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value3(String value) {
		setTipoMiembro(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value4(Integer value) {
		setSecuenciaInscripcion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value5(String value) {
		setTipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value6(String value) {
		setNombreCompleto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value7(String value) {
		setNombreGrupo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value8(String value) {
		setTelefono(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value9(String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord value10(Date value) {
		setFechaNacimiento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCursoRecord values(Integer value1, Integer value2, String value3, Integer value4, String value5, String value6, String value7, String value8, String value9, Date value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DtoMiembrosCursoRecord
	 */
	public DtoMiembrosCursoRecord() {
		super(DtoMiembrosCurso.DTO_MIEMBROS_CURSO);
	}

	/**
	 * Create a detached, initialised DtoMiembrosCursoRecord
	 */
	public DtoMiembrosCursoRecord(Integer cursoId, Integer id, String tipoMiembro, Integer secuenciaInscripcion, String tipo, String nombreCompleto, String nombreGrupo, String telefono, String email, Date fechaNacimiento) {
		super(DtoMiembrosCurso.DTO_MIEMBROS_CURSO);

		setValue(0, cursoId);
		setValue(1, id);
		setValue(2, tipoMiembro);
		setValue(3, secuenciaInscripcion);
		setValue(4, tipo);
		setValue(5, nombreCompleto);
		setValue(6, nombreGrupo);
		setValue(7, telefono);
		setValue(8, email);
		setValue(9, fechaNacimiento);
	}
}
