/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.db.tables.LiquidacionBalanceResumen;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionBalanceResumenRecord extends TableRecordImpl<LiquidacionBalanceResumenRecord> implements Record6<Short, String, String, Long, BigDecimal, BigDecimal> {

	private static final long serialVersionUID = -304931180;

	/**
	 * Setter for <code>public.liquidacion_balance_resumen.ronda_id</code>.
	 */
	public void setRondaId(Short value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.liquidacion_balance_resumen.ronda_id</code>.
	 */
	public Short getRondaId() {
		return (Short) getValue(0);
	}

	/**
	 * Setter for <code>public.liquidacion_balance_resumen.grupo_id</code>.
	 */
	public void setGrupoId(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.liquidacion_balance_resumen.grupo_id</code>.
	 */
	public String getGrupoId() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.liquidacion_balance_resumen.grupo_nombre</code>.
	 */
	public void setGrupoNombre(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.liquidacion_balance_resumen.grupo_nombre</code>.
	 */
	public String getGrupoNombre() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.liquidacion_balance_resumen.activos</code>.
	 */
	public void setActivos(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.liquidacion_balance_resumen.activos</code>.
	 */
	public Long getActivos() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>public.liquidacion_balance_resumen.balance_sin_borradores</code>.
	 */
	public void setBalanceSinBorradores(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.liquidacion_balance_resumen.balance_sin_borradores</code>.
	 */
	public BigDecimal getBalanceSinBorradores() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>public.liquidacion_balance_resumen.balance_con_borradores</code>.
	 */
	public void setBalanceConBorradores(BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.liquidacion_balance_resumen.balance_con_borradores</code>.
	 */
	public BigDecimal getBalanceConBorradores() {
		return (BigDecimal) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Short, String, String, Long, BigDecimal, BigDecimal> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Short, String, String, Long, BigDecimal, BigDecimal> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field1() {
		return LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN.RONDA_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN.GRUPO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN.GRUPO_NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN.ACTIVOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN.BALANCE_SIN_BORRADORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field6() {
		return LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN.BALANCE_CON_BORRADORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value1() {
		return getRondaId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getGrupoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getGrupoNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getActivos();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getBalanceSinBorradores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value6() {
		return getBalanceConBorradores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalanceResumenRecord value1(Short value) {
		setRondaId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalanceResumenRecord value2(String value) {
		setGrupoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalanceResumenRecord value3(String value) {
		setGrupoNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalanceResumenRecord value4(Long value) {
		setActivos(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalanceResumenRecord value5(BigDecimal value) {
		setBalanceSinBorradores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalanceResumenRecord value6(BigDecimal value) {
		setBalanceConBorradores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalanceResumenRecord values(Short value1, String value2, String value3, Long value4, BigDecimal value5, BigDecimal value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LiquidacionBalanceResumenRecord
	 */
	public LiquidacionBalanceResumenRecord() {
		super(LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN);
	}

	/**
	 * Create a detached, initialised LiquidacionBalanceResumenRecord
	 */
	public LiquidacionBalanceResumenRecord(Short rondaId, String grupoId, String grupoNombre, Long activos, BigDecimal balanceSinBorradores, BigDecimal balanceConBorradores) {
		super(LiquidacionBalanceResumen.LIQUIDACION_BALANCE_RESUMEN);

		setValue(0, rondaId);
		setValue(1, grupoId);
		setValue(2, grupoNombre);
		setValue(3, activos);
		setValue(4, balanceSinBorradores);
		setValue(5, balanceConBorradores);
	}
}
