/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;
import org.scoutsfev.cudu.db.tables.ValoresFederativos;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValoresFederativosRecord extends TableRecordImpl<ValoresFederativosRecord> implements Record11<Object, Integer, Long, Long, Long, Long, Long, Long, Long, Long, Long> {

	private static final long serialVersionUID = 563776868;

	/**
	 * Setter for <code>public.valores_federativos.ambito</code>.
	 */
	public void setAmbito(Object value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.ambito</code>.
	 */
	public Object getAmbito() {
		return (Object) getValue(0);
	}

	/**
	 * Setter for <code>public.valores_federativos.especificidad</code>.
	 */
	public void setEspecificidad(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.especificidad</code>.
	 */
	public Integer getEspecificidad() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.valores_federativos.joven</code>.
	 */
	public void setJoven(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.joven</code>.
	 */
	public Long getJoven() {
		return (Long) getValue(2);
	}

	/**
	 * Setter for <code>public.valores_federativos.kraal</code>.
	 */
	public void setKraal(Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.kraal</code>.
	 */
	public Long getKraal() {
		return (Long) getValue(3);
	}

	/**
	 * Setter for <code>public.valores_federativos.comite</code>.
	 */
	public void setComite(Long value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.comite</code>.
	 */
	public Long getComite() {
		return (Long) getValue(4);
	}

	/**
	 * Setter for <code>public.valores_federativos.colonia</code>.
	 */
	public void setColonia(Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.colonia</code>.
	 */
	public Long getColonia() {
		return (Long) getValue(5);
	}

	/**
	 * Setter for <code>public.valores_federativos.manada</code>.
	 */
	public void setManada(Long value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.manada</code>.
	 */
	public Long getManada() {
		return (Long) getValue(6);
	}

	/**
	 * Setter for <code>public.valores_federativos.exploradores</code>.
	 */
	public void setExploradores(Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.exploradores</code>.
	 */
	public Long getExploradores() {
		return (Long) getValue(7);
	}

	/**
	 * Setter for <code>public.valores_federativos.expedicion</code>.
	 */
	public void setExpedicion(Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.expedicion</code>.
	 */
	public Long getExpedicion() {
		return (Long) getValue(8);
	}

	/**
	 * Setter for <code>public.valores_federativos.ruta</code>.
	 */
	public void setRuta(Long value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.ruta</code>.
	 */
	public Long getRuta() {
		return (Long) getValue(9);
	}

	/**
	 * Setter for <code>public.valores_federativos.total</code>.
	 */
	public void setTotal(Long value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.valores_federativos.total</code>.
	 */
	public Long getTotal() {
		return (Long) getValue(10);
	}

	// -------------------------------------------------------------------------
	// Record11 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Object, Integer, Long, Long, Long, Long, Long, Long, Long, Long, Long> fieldsRow() {
		return (Row11) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row11<Object, Integer, Long, Long, Long, Long, Long, Long, Long, Long, Long> valuesRow() {
		return (Row11) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Object> field1() {
		return ValoresFederativos.VALORES_FEDERATIVOS.AMBITO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return ValoresFederativos.VALORES_FEDERATIVOS.ESPECIFICIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return ValoresFederativos.VALORES_FEDERATIVOS.JOVEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field4() {
		return ValoresFederativos.VALORES_FEDERATIVOS.KRAAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field5() {
		return ValoresFederativos.VALORES_FEDERATIVOS.COMITE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field6() {
		return ValoresFederativos.VALORES_FEDERATIVOS.COLONIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field7() {
		return ValoresFederativos.VALORES_FEDERATIVOS.MANADA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field8() {
		return ValoresFederativos.VALORES_FEDERATIVOS.EXPLORADORES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field9() {
		return ValoresFederativos.VALORES_FEDERATIVOS.EXPEDICION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field10() {
		return ValoresFederativos.VALORES_FEDERATIVOS.RUTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field11() {
		return ValoresFederativos.VALORES_FEDERATIVOS.TOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Object value1() {
		return getAmbito();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getEspecificidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getJoven();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value4() {
		return getKraal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value5() {
		return getComite();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value6() {
		return getColonia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value7() {
		return getManada();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value8() {
		return getExploradores();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value9() {
		return getExpedicion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value10() {
		return getRuta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value11() {
		return getTotal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value1(Object value) {
		setAmbito(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value2(Integer value) {
		setEspecificidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value3(Long value) {
		setJoven(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value4(Long value) {
		setKraal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value5(Long value) {
		setComite(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value6(Long value) {
		setColonia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value7(Long value) {
		setManada(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value8(Long value) {
		setExploradores(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value9(Long value) {
		setExpedicion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value10(Long value) {
		setRuta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord value11(Long value) {
		setTotal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativosRecord values(Object value1, Integer value2, Long value3, Long value4, Long value5, Long value6, Long value7, Long value8, Long value9, Long value10, Long value11) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ValoresFederativosRecord
	 */
	public ValoresFederativosRecord() {
		super(ValoresFederativos.VALORES_FEDERATIVOS);
	}

	/**
	 * Create a detached, initialised ValoresFederativosRecord
	 */
	public ValoresFederativosRecord(Object ambito, Integer especificidad, Long joven, Long kraal, Long comite, Long colonia, Long manada, Long exploradores, Long expedicion, Long ruta, Long total) {
		super(ValoresFederativos.VALORES_FEDERATIVOS);

		setValue(0, ambito);
		setValue(1, especificidad);
		setValue(2, joven);
		setValue(3, kraal);
		setValue(4, comite);
		setValue(5, colonia);
		setValue(6, manada);
		setValue(7, exploradores);
		setValue(8, expedicion);
		setValue(9, ruta);
		setValue(10, total);
	}
}
