/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.scoutsfev.cudu.dd.tables.Actividad;
import org.scoutsfev.cudu.dd.tables.AsistenteActividad;
import org.scoutsfev.cudu.dd.tables.Asociado;
import org.scoutsfev.cudu.dd.tables.Cargo;
import org.scoutsfev.cudu.dd.tables.CargoAsociado;
import org.scoutsfev.cudu.dd.tables.Curso;
import org.scoutsfev.cudu.dd.tables.CursoFormador;
import org.scoutsfev.cudu.dd.tables.CursoParticipante;
import org.scoutsfev.cudu.dd.tables.Ficha;
import org.scoutsfev.cudu.dd.tables.Grupo;
import org.scoutsfev.cudu.dd.tables.Impresion;
import org.scoutsfev.cudu.dd.tables.InformacionPago;
import org.scoutsfev.cudu.dd.tables.Liquidacion;
import org.scoutsfev.cudu.dd.tables.LiquidacionAsociado;
import org.scoutsfev.cudu.dd.tables.Ronda;
import org.scoutsfev.cudu.dd.tables.SchemaVersion;
import org.scoutsfev.cudu.dd.tables.Token;
import org.scoutsfev.cudu.dd.tables.records.ActividadRecord;
import org.scoutsfev.cudu.dd.tables.records.AsistenteActividadRecord;
import org.scoutsfev.cudu.dd.tables.records.AsociadoRecord;
import org.scoutsfev.cudu.dd.tables.records.CargoAsociadoRecord;
import org.scoutsfev.cudu.dd.tables.records.CargoRecord;
import org.scoutsfev.cudu.dd.tables.records.CursoFormadorRecord;
import org.scoutsfev.cudu.dd.tables.records.CursoParticipanteRecord;
import org.scoutsfev.cudu.dd.tables.records.CursoRecord;
import org.scoutsfev.cudu.dd.tables.records.FichaRecord;
import org.scoutsfev.cudu.dd.tables.records.GrupoRecord;
import org.scoutsfev.cudu.dd.tables.records.ImpresionRecord;
import org.scoutsfev.cudu.dd.tables.records.InformacionPagoRecord;
import org.scoutsfev.cudu.dd.tables.records.LiquidacionAsociadoRecord;
import org.scoutsfev.cudu.dd.tables.records.LiquidacionRecord;
import org.scoutsfev.cudu.dd.tables.records.RondaRecord;
import org.scoutsfev.cudu.dd.tables.records.SchemaVersionRecord;
import org.scoutsfev.cudu.dd.tables.records.TokenRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<ActividadRecord, Integer> IDENTITY_ACTIVIDAD = Identities0.IDENTITY_ACTIVIDAD;
	public static final Identity<AsociadoRecord, Integer> IDENTITY_ASOCIADO = Identities0.IDENTITY_ASOCIADO;
	public static final Identity<CargoRecord, Integer> IDENTITY_CARGO = Identities0.IDENTITY_CARGO;
	public static final Identity<CursoRecord, Integer> IDENTITY_CURSO = Identities0.IDENTITY_CURSO;
	public static final Identity<CursoParticipanteRecord, Integer> IDENTITY_CURSO_PARTICIPANTE = Identities0.IDENTITY_CURSO_PARTICIPANTE;
	public static final Identity<FichaRecord, Integer> IDENTITY_FICHA = Identities0.IDENTITY_FICHA;
	public static final Identity<LiquidacionRecord, Integer> IDENTITY_LIQUIDACION = Identities0.IDENTITY_LIQUIDACION;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<ActividadRecord> ACTIVIDAD_PKEY = UniqueKeys0.ACTIVIDAD_PKEY;
	public static final UniqueKey<AsistenteActividadRecord> ASISTENTE_ACTIVIDAD_PKEY = UniqueKeys0.ASISTENTE_ACTIVIDAD_PKEY;
	public static final UniqueKey<AsociadoRecord> PK_ASOCIADO = UniqueKeys0.PK_ASOCIADO;
	public static final UniqueKey<CargoRecord> PK_CARGO = UniqueKeys0.PK_CARGO;
	public static final UniqueKey<CargoAsociadoRecord> CARGO_ASOCIADO_PKEY = UniqueKeys0.CARGO_ASOCIADO_PKEY;
	public static final UniqueKey<CursoRecord> PK_CURSO = UniqueKeys0.PK_CURSO;
	public static final UniqueKey<CursoFormadorRecord> PK_CURSO_FORMADOR = UniqueKeys0.PK_CURSO_FORMADOR;
	public static final UniqueKey<CursoParticipanteRecord> PK_CURSO_PARTICIPANTE = UniqueKeys0.PK_CURSO_PARTICIPANTE;
	public static final UniqueKey<FichaRecord> FICHA_PKEY = UniqueKeys0.FICHA_PKEY;
	public static final UniqueKey<GrupoRecord> PK_GRUPO = UniqueKeys0.PK_GRUPO;
	public static final UniqueKey<ImpresionRecord> IMPRESION_PKEY = UniqueKeys0.IMPRESION_PKEY;
	public static final UniqueKey<InformacionPagoRecord> PK_INFORMACION_PAGO = UniqueKeys0.PK_INFORMACION_PAGO;
	public static final UniqueKey<LiquidacionRecord> PK_LIQUIDACION = UniqueKeys0.PK_LIQUIDACION;
	public static final UniqueKey<LiquidacionAsociadoRecord> PK_LIQUIDACION_ASOCIADO = UniqueKeys0.PK_LIQUIDACION_ASOCIADO;
	public static final UniqueKey<RondaRecord> PK_RONDA = UniqueKeys0.PK_RONDA;
	public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = UniqueKeys0.SCHEMA_VERSION_PK;
	public static final UniqueKey<TokenRecord> TOKEN_PKEY = UniqueKeys0.TOKEN_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<ActividadRecord, GrupoRecord> ACTIVIDAD__ACTIVIDAD_GRUPO_ID_FKEY = ForeignKeys0.ACTIVIDAD__ACTIVIDAD_GRUPO_ID_FKEY;
	public static final ForeignKey<AsistenteActividadRecord, ActividadRecord> ASISTENTE_ACTIVIDAD__ASISTENTE_ACTIVIDAD_ACTIVIDAD_ID_FKEY = ForeignKeys0.ASISTENTE_ACTIVIDAD__ASISTENTE_ACTIVIDAD_ACTIVIDAD_ID_FKEY;
	public static final ForeignKey<AsistenteActividadRecord, AsociadoRecord> ASISTENTE_ACTIVIDAD__ASISTENTE_ACTIVIDAD_ASOCIADO_ID_FKEY = ForeignKeys0.ASISTENTE_ACTIVIDAD__ASISTENTE_ACTIVIDAD_ASOCIADO_ID_FKEY;
	public static final ForeignKey<AsociadoRecord, GrupoRecord> ASOCIADO__FK_ASOCIADO_GRUPO = ForeignKeys0.ASOCIADO__FK_ASOCIADO_GRUPO;
	public static final ForeignKey<CursoRecord, AsociadoRecord> CURSO__FK_CURSO_COORDINADORID_ASOCIADO = ForeignKeys0.CURSO__FK_CURSO_COORDINADORID_ASOCIADO;
	public static final ForeignKey<CursoFormadorRecord, CursoRecord> CURSO_FORMADOR__FK_CURSO_FORMADOR_CURSO = ForeignKeys0.CURSO_FORMADOR__FK_CURSO_FORMADOR_CURSO;
	public static final ForeignKey<CursoFormadorRecord, AsociadoRecord> CURSO_FORMADOR__FK_CURSO_FORMADOR_FORMADOR = ForeignKeys0.CURSO_FORMADOR__FK_CURSO_FORMADOR_FORMADOR;
	public static final ForeignKey<CursoParticipanteRecord, CursoRecord> CURSO_PARTICIPANTE__FK_CURSO_PARTICIPANTE_CURSO = ForeignKeys0.CURSO_PARTICIPANTE__FK_CURSO_PARTICIPANTE_CURSO;
	public static final ForeignKey<CursoParticipanteRecord, AsociadoRecord> CURSO_PARTICIPANTE__FK_CURSO_PARTICIPANTE_PARTICIPANTE = ForeignKeys0.CURSO_PARTICIPANTE__FK_CURSO_PARTICIPANTE_PARTICIPANTE;
	public static final ForeignKey<LiquidacionRecord, RondaRecord> LIQUIDACION__FK_LIQUIDACION_RONDA = ForeignKeys0.LIQUIDACION__FK_LIQUIDACION_RONDA;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<ActividadRecord, Integer> IDENTITY_ACTIVIDAD = createIdentity(Actividad.ACTIVIDAD, Actividad.ACTIVIDAD.ID);
		public static Identity<AsociadoRecord, Integer> IDENTITY_ASOCIADO = createIdentity(Asociado.ASOCIADO, Asociado.ASOCIADO.ID);
		public static Identity<CargoRecord, Integer> IDENTITY_CARGO = createIdentity(Cargo.CARGO, Cargo.CARGO.ID);
		public static Identity<CursoRecord, Integer> IDENTITY_CURSO = createIdentity(Curso.CURSO, Curso.CURSO.ID);
		public static Identity<CursoParticipanteRecord, Integer> IDENTITY_CURSO_PARTICIPANTE = createIdentity(CursoParticipante.CURSO_PARTICIPANTE, CursoParticipante.CURSO_PARTICIPANTE.SECUENCIA_INSCRIPCION);
		public static Identity<FichaRecord, Integer> IDENTITY_FICHA = createIdentity(Ficha.FICHA, Ficha.FICHA.ID);
		public static Identity<LiquidacionRecord, Integer> IDENTITY_LIQUIDACION = createIdentity(Liquidacion.LIQUIDACION, Liquidacion.LIQUIDACION.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<ActividadRecord> ACTIVIDAD_PKEY = createUniqueKey(Actividad.ACTIVIDAD, Actividad.ACTIVIDAD.ID);
		public static final UniqueKey<AsistenteActividadRecord> ASISTENTE_ACTIVIDAD_PKEY = createUniqueKey(AsistenteActividad.ASISTENTE_ACTIVIDAD, AsistenteActividad.ASISTENTE_ACTIVIDAD.ASOCIADO_ID, AsistenteActividad.ASISTENTE_ACTIVIDAD.ACTIVIDAD_ID);
		public static final UniqueKey<AsociadoRecord> PK_ASOCIADO = createUniqueKey(Asociado.ASOCIADO, Asociado.ASOCIADO.ID);
		public static final UniqueKey<CargoRecord> PK_CARGO = createUniqueKey(Cargo.CARGO, Cargo.CARGO.ID);
		public static final UniqueKey<CargoAsociadoRecord> CARGO_ASOCIADO_PKEY = createUniqueKey(CargoAsociado.CARGO_ASOCIADO, CargoAsociado.CARGO_ASOCIADO.CARGO_ID, CargoAsociado.CARGO_ASOCIADO.ASOCIADO_ID);
		public static final UniqueKey<CursoRecord> PK_CURSO = createUniqueKey(Curso.CURSO, Curso.CURSO.ID);
		public static final UniqueKey<CursoFormadorRecord> PK_CURSO_FORMADOR = createUniqueKey(CursoFormador.CURSO_FORMADOR, CursoFormador.CURSO_FORMADOR.CURSO_ID, CursoFormador.CURSO_FORMADOR.ASOCIADO_ID);
		public static final UniqueKey<CursoParticipanteRecord> PK_CURSO_PARTICIPANTE = createUniqueKey(CursoParticipante.CURSO_PARTICIPANTE, CursoParticipante.CURSO_PARTICIPANTE.CURSO_ID, CursoParticipante.CURSO_PARTICIPANTE.ASOCIADO_ID);
		public static final UniqueKey<FichaRecord> FICHA_PKEY = createUniqueKey(Ficha.FICHA, Ficha.FICHA.ID, Ficha.FICHA.LENGUAJE);
		public static final UniqueKey<GrupoRecord> PK_GRUPO = createUniqueKey(Grupo.GRUPO, Grupo.GRUPO.ID);
		public static final UniqueKey<ImpresionRecord> IMPRESION_PKEY = createUniqueKey(Impresion.IMPRESION, Impresion.IMPRESION.FICHERO, Impresion.IMPRESION.USUARIO_ID);
		public static final UniqueKey<InformacionPagoRecord> PK_INFORMACION_PAGO = createUniqueKey(InformacionPago.INFORMACION_PAGO, InformacionPago.INFORMACION_PAGO.ASOCIACIONID);
		public static final UniqueKey<LiquidacionRecord> PK_LIQUIDACION = createUniqueKey(Liquidacion.LIQUIDACION, Liquidacion.LIQUIDACION.ID);
		public static final UniqueKey<LiquidacionAsociadoRecord> PK_LIQUIDACION_ASOCIADO = createUniqueKey(LiquidacionAsociado.LIQUIDACION_ASOCIADO, LiquidacionAsociado.LIQUIDACION_ASOCIADO.LIQUIDACION_ID, LiquidacionAsociado.LIQUIDACION_ASOCIADO.ASOCIADO_ID);
		public static final UniqueKey<RondaRecord> PK_RONDA = createUniqueKey(Ronda.RONDA, Ronda.RONDA.ID);
		public static final UniqueKey<SchemaVersionRecord> SCHEMA_VERSION_PK = createUniqueKey(SchemaVersion.SCHEMA_VERSION, SchemaVersion.SCHEMA_VERSION.VERSION);
		public static final UniqueKey<TokenRecord> TOKEN_PKEY = createUniqueKey(Token.TOKEN, Token.TOKEN.TOKEN_);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<ActividadRecord, GrupoRecord> ACTIVIDAD__ACTIVIDAD_GRUPO_ID_FKEY = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_GRUPO, Actividad.ACTIVIDAD, Actividad.ACTIVIDAD.GRUPO_ID);
		public static final ForeignKey<AsistenteActividadRecord, ActividadRecord> ASISTENTE_ACTIVIDAD__ASISTENTE_ACTIVIDAD_ACTIVIDAD_ID_FKEY = createForeignKey(org.scoutsfev.cudu.dd.Keys.ACTIVIDAD_PKEY, AsistenteActividad.ASISTENTE_ACTIVIDAD, AsistenteActividad.ASISTENTE_ACTIVIDAD.ACTIVIDAD_ID);
		public static final ForeignKey<AsistenteActividadRecord, AsociadoRecord> ASISTENTE_ACTIVIDAD__ASISTENTE_ACTIVIDAD_ASOCIADO_ID_FKEY = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_ASOCIADO, AsistenteActividad.ASISTENTE_ACTIVIDAD, AsistenteActividad.ASISTENTE_ACTIVIDAD.ASOCIADO_ID);
		public static final ForeignKey<AsociadoRecord, GrupoRecord> ASOCIADO__FK_ASOCIADO_GRUPO = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_GRUPO, Asociado.ASOCIADO, Asociado.ASOCIADO.GRUPO_ID);
		public static final ForeignKey<CursoRecord, AsociadoRecord> CURSO__FK_CURSO_COORDINADORID_ASOCIADO = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_ASOCIADO, Curso.CURSO, Curso.CURSO.COORDINADOR_ID);
		public static final ForeignKey<CursoFormadorRecord, CursoRecord> CURSO_FORMADOR__FK_CURSO_FORMADOR_CURSO = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_CURSO, CursoFormador.CURSO_FORMADOR, CursoFormador.CURSO_FORMADOR.CURSO_ID);
		public static final ForeignKey<CursoFormadorRecord, AsociadoRecord> CURSO_FORMADOR__FK_CURSO_FORMADOR_FORMADOR = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_ASOCIADO, CursoFormador.CURSO_FORMADOR, CursoFormador.CURSO_FORMADOR.ASOCIADO_ID);
		public static final ForeignKey<CursoParticipanteRecord, CursoRecord> CURSO_PARTICIPANTE__FK_CURSO_PARTICIPANTE_CURSO = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_CURSO, CursoParticipante.CURSO_PARTICIPANTE, CursoParticipante.CURSO_PARTICIPANTE.CURSO_ID);
		public static final ForeignKey<CursoParticipanteRecord, AsociadoRecord> CURSO_PARTICIPANTE__FK_CURSO_PARTICIPANTE_PARTICIPANTE = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_ASOCIADO, CursoParticipante.CURSO_PARTICIPANTE, CursoParticipante.CURSO_PARTICIPANTE.ASOCIADO_ID);
		public static final ForeignKey<LiquidacionRecord, RondaRecord> LIQUIDACION__FK_LIQUIDACION_RONDA = createForeignKey(org.scoutsfev.cudu.dd.Keys.PK_RONDA, Liquidacion.LIQUIDACION, Liquidacion.LIQUIDACION.RONDA_ID);
	}
}
