kind: ConfigMap
apiVersion: v1
metadata:
  name: {{cudu_service}}-configmap
  namespace: {{cudu_kube_ns}}
data:
  application.properties: |  
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.datasource.url=jdbc:postgresql://{{postgres_back_host}}:5432/{{cudu_db_name}}
    spring.datasource.username={{cudu_db_user}}
    spring.datasource.password={{cudu_db_password}}
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
---
apiVersion: v1
kind: Service
metadata:
  name: {{cudu_service}}
  namespace: {{cudu_kube_ns}}
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: {{cudu_service}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{cudu_service}}
  namespace: {{cudu_kube_ns}}
  labels:
    app: {{cudu_service}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{cudu_service}}
  template:
    metadata:
      labels:
        app: {{cudu_service}}  
    spec:
      nodeName: {{cudu_node}}
      containers:
      - image: {{cudu_backend_image}}
        name: "{{cudu_service}}-backend"
        ports:
        - containerPort: 8080
          name: backend
        env:
        - name: TZ
          value: Europe/Andorra
        volumeMounts:
        - name: application-properties
          mountPath: /srv/app/config/application.properties
          subPath: application.properties
      - image: {{cudu_frontend_image}}
        name: "{{cudu_service}}"
        ports:
        - containerPort: 80
          name: frontend
        env:
        - name: TZ
          value: Europe/Andorra
      volumes:
      - name: application-properties
        configMap:
          name: {{cudu_service}}-configmap
          items:
          - key: application.properties
            path: application.properties
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - {{kube_master_node}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{cudu_service}}
  namespace: {{cudu_kube_ns}}
spec:
  rules:
  - host: "{{cudu_service}}.{{office_domain}}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{cudu_service}}
          servicePort: web
