// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/54f064352a3615443f7bff4198078db15e28247b/moment/moment.d.ts
declare var moment: moment.MomentStatic;
