/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.dd.Public;
import org.scoutsfev.cudu.dd.tables.records.DtoMiembrosCursoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoMiembrosCurso extends TableImpl<DtoMiembrosCursoRecord> {

	private static final long serialVersionUID = -70430600;

	/**
	 * The reference instance of <code>public.dto_miembros_curso</code>
	 */
	public static final DtoMiembrosCurso DTO_MIEMBROS_CURSO = new DtoMiembrosCurso();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DtoMiembrosCursoRecord> getRecordType() {
		return DtoMiembrosCursoRecord.class;
	}

	/**
	 * The column <code>public.dto_miembros_curso.curso_id</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, Integer> CURSO_ID = createField("curso_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.dto_miembros_curso.id</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.dto_miembros_curso.tipo_miembro</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, String> TIPO_MIEMBRO = createField("tipo_miembro", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.dto_miembros_curso.secuencia_inscripcion</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, Integer> SECUENCIA_INSCRIPCION = createField("secuencia_inscripcion", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.dto_miembros_curso.tipo</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

	/**
	 * The column <code>public.dto_miembros_curso.nombre_completo</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, String> NOMBRE_COMPLETO = createField("nombre_completo", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.dto_miembros_curso.nombre_grupo</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, String> NOMBRE_GRUPO = createField("nombre_grupo", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.dto_miembros_curso.telefono</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, String> TELEFONO = createField("telefono", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>public.dto_miembros_curso.email</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.dto_miembros_curso.fecha_nacimiento</code>.
	 */
	public final TableField<DtoMiembrosCursoRecord, Date> FECHA_NACIMIENTO = createField("fecha_nacimiento", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * Create a <code>public.dto_miembros_curso</code> table reference
	 */
	public DtoMiembrosCurso() {
		this("dto_miembros_curso", null);
	}

	/**
	 * Create an aliased <code>public.dto_miembros_curso</code> table reference
	 */
	public DtoMiembrosCurso(String alias) {
		this(alias, DTO_MIEMBROS_CURSO);
	}

	private DtoMiembrosCurso(String alias, Table<DtoMiembrosCursoRecord> aliased) {
		this(alias, aliased, null);
	}

	private DtoMiembrosCurso(String alias, Table<DtoMiembrosCursoRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoMiembrosCurso as(String alias) {
		return new DtoMiembrosCurso(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DtoMiembrosCurso rename(String name) {
		return new DtoMiembrosCurso(name, null);
	}
}
