/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.dd.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.dd.Keys;
import org.scoutsfev.cudu.dd.Public;
import org.scoutsfev.cudu.dd.tables.records.FichaRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ficha extends TableImpl<FichaRecord> {

	private static final long serialVersionUID = 1681716966;

	/**
	 * The reference instance of <code>public.ficha</code>
	 */
	public static final Ficha FICHA = new Ficha();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<FichaRecord> getRecordType() {
		return FichaRecord.class;
	}

	/**
	 * The column <code>public.ficha.id</code>.
	 */
	public final TableField<FichaRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.ficha.lenguaje</code>.
	 */
	public final TableField<FichaRecord, String> LENGUAJE = createField("lenguaje", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false), this, "");

	/**
	 * The column <code>public.ficha.nombre</code>.
	 */
	public final TableField<FichaRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * The column <code>public.ficha.plantilla</code>.
	 */
	public final TableField<FichaRecord, String> PLANTILLA = createField("plantilla", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * The column <code>public.ficha.tipo_entidad</code>.
	 */
	public final TableField<FichaRecord, Integer> TIPO_ENTIDAD = createField("tipo_entidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.ficha.tipo_ficha</code>.
	 */
	public final TableField<FichaRecord, Integer> TIPO_FICHA = createField("tipo_ficha", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.ficha</code> table reference
	 */
	public Ficha() {
		this("ficha", null);
	}

	/**
	 * Create an aliased <code>public.ficha</code> table reference
	 */
	public Ficha(String alias) {
		this(alias, FICHA);
	}

	private Ficha(String alias, Table<FichaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Ficha(String alias, Table<FichaRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<FichaRecord, Integer> getIdentity() {
		return Keys.IDENTITY_FICHA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<FichaRecord> getPrimaryKey() {
		return Keys.FICHA_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<FichaRecord>> getKeys() {
		return Arrays.<UniqueKey<FichaRecord>>asList(Keys.FICHA_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Ficha as(String alias) {
		return new Ficha(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Ficha rename(String name) {
		return new Ficha(name, null);
	}
}
