- hosts: wilma
  become: true
  vars_files:
  - vars/main.yml
  collections:
  - jamgo.base

  vars_prompt:
    - name: "purge_service"
      prompt: "Purging will also remove the associated database. Are you sure (yes/NO)?"
      private: no

  tasks:
  
# ... Delete project service

  - name: Delete project service
    include_role:
      name: kube-utils
      tasks_from: kube-delete-template
    vars:
      template_name: "{{cudu_service}}-service"
    when: purge_service | bool

# ... Drop database.

  - name: Drop project db
    command: "{{item}}"
    with_items:
      - kubectl exec {{postgres_back_service}} -n {{postgres_back_kube_ns}} -- psql -U {{postgres_back_user}} -c 'drop database if exists "{{cudu_db_name}}";'
      - kubectl exec {{postgres_back_service}} -n {{postgres_back_kube_ns}} -- psql -U {{postgres_back_user}} -c "drop user if exists {{cudu_db_user}};"
    when: purge_service | bool
    