- hosts: wilma
  become: true
  vars_files:
  - vars/main.yml
  collections:
  - jamgo.base

  tasks:
  
# ... Delete project service

  - name: Delete project service
    include_role:
      name: kube-utils
      tasks_from: kube-delete-template
    vars:
      template_name: "{{cudu_service}}-service"
