/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Keys;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.AsociadoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Asociado extends TableImpl<AsociadoRecord> {

	private static final long serialVersionUID = -963167914;

	/**
	 * The reference instance of <code>public.asociado</code>
	 */
	public static final Asociado ASOCIADO = new Asociado();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AsociadoRecord> getRecordType() {
		return AsociadoRecord.class;
	}

	/**
	 * The column <code>public.asociado.id</code>.
	 */
	public final TableField<AsociadoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.tipo</code>.
	 */
	public final TableField<AsociadoRecord, String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>public.asociado.grupo_id</code>.
	 */
	public final TableField<AsociadoRecord, String> GRUPO_ID = createField("grupo_id", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * The column <code>public.asociado.nombre</code>.
	 */
	public final TableField<AsociadoRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>public.asociado.apellidos</code>.
	 */
	public final TableField<AsociadoRecord, String> APELLIDOS = createField("apellidos", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>public.asociado.sexo</code>.
	 */
	public final TableField<AsociadoRecord, String> SEXO = createField("sexo", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

	/**
	 * The column <code>public.asociado.fecha_nacimiento</code>.
	 */
	public final TableField<AsociadoRecord, Date> FECHA_NACIMIENTO = createField("fecha_nacimiento", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>public.asociado.dni</code>.
	 */
	public final TableField<AsociadoRecord, String> DNI = createField("dni", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>public.asociado.seguridad_social</code>.
	 */
	public final TableField<AsociadoRecord, String> SEGURIDAD_SOCIAL = createField("seguridad_social", org.jooq.impl.SQLDataType.VARCHAR.length(12), this, "");

	/**
	 * The column <code>public.asociado.tiene_seguro_privado</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> TIENE_SEGURO_PRIVADO = createField("tiene_seguro_privado", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.direccion</code>.
	 */
	public final TableField<AsociadoRecord, String> DIRECCION = createField("direccion", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.asociado.codigo_postal</code>.
	 */
	public final TableField<AsociadoRecord, Integer> CODIGO_POSTAL = createField("codigo_postal", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.asociado.telefono_casa</code>.
	 */
	public final TableField<AsociadoRecord, String> TELEFONO_CASA = createField("telefono_casa", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>public.asociado.telefono_movil</code>.
	 */
	public final TableField<AsociadoRecord, String> TELEFONO_MOVIL = createField("telefono_movil", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>public.asociado.email</code>.
	 */
	public final TableField<AsociadoRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.asociado.municipio</code>.
	 */
	public final TableField<AsociadoRecord, String> MUNICIPIO = createField("municipio", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.asociado.tiene_tutor_legal</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> TIENE_TUTOR_LEGAL = createField("tiene_tutor_legal", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.padres_divorciados</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> PADRES_DIVORCIADOS = createField("padres_divorciados", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.padre_nombre</code>.
	 */
	public final TableField<AsociadoRecord, String> PADRE_NOMBRE = createField("padre_nombre", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>public.asociado.padre_telefono</code>.
	 */
	public final TableField<AsociadoRecord, String> PADRE_TELEFONO = createField("padre_telefono", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>public.asociado.padre_email</code>.
	 */
	public final TableField<AsociadoRecord, String> PADRE_EMAIL = createField("padre_email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.asociado.madre_nombre</code>.
	 */
	public final TableField<AsociadoRecord, String> MADRE_NOMBRE = createField("madre_nombre", org.jooq.impl.SQLDataType.VARCHAR.length(250), this, "");

	/**
	 * The column <code>public.asociado.madre_telefono</code>.
	 */
	public final TableField<AsociadoRecord, String> MADRE_TELEFONO = createField("madre_telefono", org.jooq.impl.SQLDataType.VARCHAR.length(15), this, "");

	/**
	 * The column <code>public.asociado.madre_email</code>.
	 */
	public final TableField<AsociadoRecord, String> MADRE_EMAIL = createField("madre_email", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>public.asociado.fecha_alta</code>.
	 */
	public final TableField<AsociadoRecord, Timestamp> FECHA_ALTA = createField("fecha_alta", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.fecha_baja</code>.
	 */
	public final TableField<AsociadoRecord, Timestamp> FECHA_BAJA = createField("fecha_baja", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.asociado.fecha_actualizacion</code>.
	 */
	public final TableField<AsociadoRecord, Timestamp> FECHA_ACTUALIZACION = createField("fecha_actualizacion", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.rama_colonia</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> RAMA_COLONIA = createField("rama_colonia", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.rama_manada</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> RAMA_MANADA = createField("rama_manada", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.rama_exploradores</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> RAMA_EXPLORADORES = createField("rama_exploradores", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.rama_expedicion</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> RAMA_EXPEDICION = createField("rama_expedicion", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.rama_ruta</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> RAMA_RUTA = createField("rama_ruta", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.activo</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> ACTIVO = createField("activo", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

	/**
	 * The column <code>public.asociado.usuario_activo</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> USUARIO_ACTIVO = createField("usuario_activo", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.password</code>.
	 */
	public final TableField<AsociadoRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.asociado.requiere_captcha</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> REQUIERE_CAPTCHA = createField("requiere_captcha", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.lenguaje</code>.
	 */
	public final TableField<AsociadoRecord, String> LENGUAJE = createField("lenguaje", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * The column <code>public.asociado.ambito_edicion</code>.
	 */
	public final TableField<AsociadoRecord, String> AMBITO_EDICION = createField("ambito_edicion", org.jooq.impl.SQLDataType.CHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>public.asociado.restriccion_asociacion</code>.
	 */
	public final TableField<AsociadoRecord, Integer> RESTRICCION_ASOCIACION = createField("restriccion_asociacion", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.asociado.no_puede_editar_datos_del_grupo</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> NO_PUEDE_EDITAR_DATOS_DEL_GRUPO = createField("no_puede_editar_datos_del_grupo", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.no_puede_editar_otras_ramas</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> NO_PUEDE_EDITAR_OTRAS_RAMAS = createField("no_puede_editar_otras_ramas", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.solo_lectura</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> SOLO_LECTURA = createField("solo_lectura", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.estudios</code>.
	 */
	public final TableField<AsociadoRecord, String> ESTUDIOS = createField("estudios", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>public.asociado.profesion</code>.
	 */
	public final TableField<AsociadoRecord, String> PROFESION = createField("profesion", org.jooq.impl.SQLDataType.VARCHAR.length(128), this, "");

	/**
	 * The column <code>public.asociado.hermanos_en_el_grupo</code>.
	 */
	public final TableField<AsociadoRecord, Boolean> HERMANOS_EN_EL_GRUPO = createField("hermanos_en_el_grupo", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.asociado.fecha_usuario_creado</code>.
	 */
	public final TableField<AsociadoRecord, Timestamp> FECHA_USUARIO_CREADO = createField("fecha_usuario_creado", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.asociado.fecha_usuario_visto</code>.
	 */
	public final TableField<AsociadoRecord, Timestamp> FECHA_USUARIO_VISTO = createField("fecha_usuario_visto", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.asociado.usuario_creado_por_id</code>.
	 */
	public final TableField<AsociadoRecord, Integer> USUARIO_CREADO_POR_ID = createField("usuario_creado_por_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.asociado.usuario_creado_por_nombre</code>.
	 */
	public final TableField<AsociadoRecord, String> USUARIO_CREADO_POR_NOMBRE = createField("usuario_creado_por_nombre", org.jooq.impl.SQLDataType.VARCHAR.length(130), this, "");

	/**
	 * The column <code>public.asociado.notas</code>.
	 */
	public final TableField<AsociadoRecord, String> NOTAS = createField("notas", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.asociado.email_contacto</code>.
	 */
	public final TableField<AsociadoRecord, String> EMAIL_CONTACTO = createField("email_contacto", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>public.asociado</code> table reference
	 */
	public Asociado() {
		this("asociado", null);
	}

	/**
	 * Create an aliased <code>public.asociado</code> table reference
	 */
	public Asociado(String alias) {
		this(alias, ASOCIADO);
	}

	private Asociado(String alias, Table<AsociadoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Asociado(String alias, Table<AsociadoRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<AsociadoRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ASOCIADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AsociadoRecord> getPrimaryKey() {
		return Keys.PK_ASOCIADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AsociadoRecord>> getKeys() {
		return Arrays.<UniqueKey<AsociadoRecord>>asList(Keys.PK_ASOCIADO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AsociadoRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AsociadoRecord, ?>>asList(Keys.ASOCIADO__FK_ASOCIADO_GRUPO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Asociado as(String alias) {
		return new Asociado(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Asociado rename(String name) {
		return new Asociado(name, null);
	}
}
