/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Keys;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.CargoAsociadoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CargoAsociado extends TableImpl<CargoAsociadoRecord> {

	private static final long serialVersionUID = -424947961;

	/**
	 * The reference instance of <code>public.cargo_asociado</code>
	 */
	public static final CargoAsociado CARGO_ASOCIADO = new CargoAsociado();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CargoAsociadoRecord> getRecordType() {
		return CargoAsociadoRecord.class;
	}

	/**
	 * The column <code>public.cargo_asociado.cargo_id</code>.
	 */
	public final TableField<CargoAsociadoRecord, Integer> CARGO_ID = createField("cargo_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.cargo_asociado.asociado_id</code>.
	 */
	public final TableField<CargoAsociadoRecord, Integer> ASOCIADO_ID = createField("asociado_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.cargo_asociado</code> table reference
	 */
	public CargoAsociado() {
		this("cargo_asociado", null);
	}

	/**
	 * Create an aliased <code>public.cargo_asociado</code> table reference
	 */
	public CargoAsociado(String alias) {
		this(alias, CARGO_ASOCIADO);
	}

	private CargoAsociado(String alias, Table<CargoAsociadoRecord> aliased) {
		this(alias, aliased, null);
	}

	private CargoAsociado(String alias, Table<CargoAsociadoRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CargoAsociadoRecord> getPrimaryKey() {
		return Keys.CARGO_ASOCIADO_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CargoAsociadoRecord>> getKeys() {
		return Arrays.<UniqueKey<CargoAsociadoRecord>>asList(Keys.CARGO_ASOCIADO_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CargoAsociado as(String alias) {
		return new CargoAsociado(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CargoAsociado rename(String name) {
		return new CargoAsociado(name, null);
	}
}
