/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.DtoDatosGrupoRamaRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoDatosGrupoRama extends TableImpl<DtoDatosGrupoRamaRecord> {

	private static final long serialVersionUID = 268409534;

	/**
	 * The reference instance of <code>public.dto_datos_grupo_rama</code>
	 */
	public static final DtoDatosGrupoRama DTO_DATOS_GRUPO_RAMA = new DtoDatosGrupoRama();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<DtoDatosGrupoRamaRecord> getRecordType() {
		return DtoDatosGrupoRamaRecord.class;
	}

	/**
	 * The column <code>public.dto_datos_grupo_rama.grupo_id</code>.
	 */
	public final TableField<DtoDatosGrupoRamaRecord, String> GRUPO_ID = createField("grupo_id", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * The column <code>public.dto_datos_grupo_rama.colonia</code>.
	 */
	public final TableField<DtoDatosGrupoRamaRecord, Long> COLONIA = createField("colonia", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.dto_datos_grupo_rama.manada</code>.
	 */
	public final TableField<DtoDatosGrupoRamaRecord, Long> MANADA = createField("manada", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.dto_datos_grupo_rama.exploradores</code>.
	 */
	public final TableField<DtoDatosGrupoRamaRecord, Long> EXPLORADORES = createField("exploradores", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.dto_datos_grupo_rama.expedicion</code>.
	 */
	public final TableField<DtoDatosGrupoRamaRecord, Long> EXPEDICION = createField("expedicion", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.dto_datos_grupo_rama.ruta</code>.
	 */
	public final TableField<DtoDatosGrupoRamaRecord, Long> RUTA = createField("ruta", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.dto_datos_grupo_rama</code> table reference
	 */
	public DtoDatosGrupoRama() {
		this("dto_datos_grupo_rama", null);
	}

	/**
	 * Create an aliased <code>public.dto_datos_grupo_rama</code> table reference
	 */
	public DtoDatosGrupoRama(String alias) {
		this(alias, DTO_DATOS_GRUPO_RAMA);
	}

	private DtoDatosGrupoRama(String alias, Table<DtoDatosGrupoRamaRecord> aliased) {
		this(alias, aliased, null);
	}

	private DtoDatosGrupoRama(String alias, Table<DtoDatosGrupoRamaRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DtoDatosGrupoRama as(String alias) {
		return new DtoDatosGrupoRama(alias, this);
	}

	/**
	 * Rename this table
	 */
	public DtoDatosGrupoRama rename(String name) {
		return new DtoDatosGrupoRama(name, null);
	}
}
