/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Keys;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.ImpresionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Impresion extends TableImpl<ImpresionRecord> {

	private static final long serialVersionUID = -1287604471;

	/**
	 * The reference instance of <code>public.impresion</code>
	 */
	public static final Impresion IMPRESION = new Impresion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ImpresionRecord> getRecordType() {
		return ImpresionRecord.class;
	}

	/**
	 * The column <code>public.impresion.fichero</code>.
	 */
	public final TableField<ImpresionRecord, String> FICHERO = createField("fichero", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>public.impresion.usuario_id</code>.
	 */
	public final TableField<ImpresionRecord, Integer> USUARIO_ID = createField("usuario_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.impresion.fecha</code>.
	 */
	public final TableField<ImpresionRecord, Timestamp> FECHA = createField("fecha", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * Create a <code>public.impresion</code> table reference
	 */
	public Impresion() {
		this("impresion", null);
	}

	/**
	 * Create an aliased <code>public.impresion</code> table reference
	 */
	public Impresion(String alias) {
		this(alias, IMPRESION);
	}

	private Impresion(String alias, Table<ImpresionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Impresion(String alias, Table<ImpresionRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ImpresionRecord> getPrimaryKey() {
		return Keys.IMPRESION_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ImpresionRecord>> getKeys() {
		return Arrays.<UniqueKey<ImpresionRecord>>asList(Keys.IMPRESION_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Impresion as(String alias) {
		return new Impresion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Impresion rename(String name) {
		return new Impresion(name, null);
	}
}
