/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.LiquidacionBalanceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionBalance extends TableImpl<LiquidacionBalanceRecord> {

	private static final long serialVersionUID = -855645659;

	/**
	 * The reference instance of <code>public.liquidacion_balance</code>
	 */
	public static final LiquidacionBalance LIQUIDACION_BALANCE = new LiquidacionBalance();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LiquidacionBalanceRecord> getRecordType() {
		return LiquidacionBalanceRecord.class;
	}

	/**
	 * The column <code>public.liquidacion_balance.grupo_id</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, String> GRUPO_ID = createField("grupo_id", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * The column <code>public.liquidacion_balance.ronda_id</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, Short> RONDA_ID = createField("ronda_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.liquidacion_balance.liquidacion_id</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, Integer> LIQUIDACION_ID = createField("liquidacion_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.liquidacion_balance.activos</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, Long> ACTIVOS = createField("activos", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.liquidacion_balance.diferencia</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, Long> DIFERENCIA = createField("diferencia", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.liquidacion_balance.precio_unitario</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, BigDecimal> PRECIO_UNITARIO = createField("precio_unitario", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>public.liquidacion_balance.subtotal</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, BigDecimal> SUBTOTAL = createField("subtotal", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>public.liquidacion_balance.ajuste_manual</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, BigDecimal> AJUSTE_MANUAL = createField("ajuste_manual", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>public.liquidacion_balance.pagado</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, BigDecimal> PAGADO = createField("pagado", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>public.liquidacion_balance.balance</code>.
	 */
	public final TableField<LiquidacionBalanceRecord, BigDecimal> BALANCE = createField("balance", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * Create a <code>public.liquidacion_balance</code> table reference
	 */
	public LiquidacionBalance() {
		this("liquidacion_balance", null);
	}

	/**
	 * Create an aliased <code>public.liquidacion_balance</code> table reference
	 */
	public LiquidacionBalance(String alias) {
		this(alias, LIQUIDACION_BALANCE);
	}

	private LiquidacionBalance(String alias, Table<LiquidacionBalanceRecord> aliased) {
		this(alias, aliased, null);
	}

	private LiquidacionBalance(String alias, Table<LiquidacionBalanceRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionBalance as(String alias) {
		return new LiquidacionBalance(alias, this);
	}

	/**
	 * Rename this table
	 */
	public LiquidacionBalance rename(String name) {
		return new LiquidacionBalance(name, null);
	}
}
