/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Keys;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.LiquidacionAsociadoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionAsociado extends TableImpl<LiquidacionAsociadoRecord> {

	private static final long serialVersionUID = 201100995;

	/**
	 * The reference instance of <code>public.liquidacion_asociado</code>
	 */
	public static final LiquidacionAsociado LIQUIDACION_ASOCIADO = new LiquidacionAsociado();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LiquidacionAsociadoRecord> getRecordType() {
		return LiquidacionAsociadoRecord.class;
	}

	/**
	 * The column <code>public.liquidacion_asociado.liquidacion_id</code>.
	 */
	public final TableField<LiquidacionAsociadoRecord, Integer> LIQUIDACION_ID = createField("liquidacion_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.liquidacion_asociado.asociado_id</code>.
	 */
	public final TableField<LiquidacionAsociadoRecord, Integer> ASOCIADO_ID = createField("asociado_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.liquidacion_asociado.alta</code>.
	 */
	public final TableField<LiquidacionAsociadoRecord, Boolean> ALTA = createField("alta", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.liquidacion_asociado.creado_en</code>.
	 */
	public final TableField<LiquidacionAsociadoRecord, Timestamp> CREADO_EN = createField("creado_en", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.liquidacion_asociado</code> table reference
	 */
	public LiquidacionAsociado() {
		this("liquidacion_asociado", null);
	}

	/**
	 * Create an aliased <code>public.liquidacion_asociado</code> table reference
	 */
	public LiquidacionAsociado(String alias) {
		this(alias, LIQUIDACION_ASOCIADO);
	}

	private LiquidacionAsociado(String alias, Table<LiquidacionAsociadoRecord> aliased) {
		this(alias, aliased, null);
	}

	private LiquidacionAsociado(String alias, Table<LiquidacionAsociadoRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<LiquidacionAsociadoRecord> getPrimaryKey() {
		return Keys.PK_LIQUIDACION_ASOCIADO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<LiquidacionAsociadoRecord>> getKeys() {
		return Arrays.<UniqueKey<LiquidacionAsociadoRecord>>asList(Keys.PK_LIQUIDACION_ASOCIADO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionAsociado as(String alias) {
		return new LiquidacionAsociado(alias, this);
	}

	/**
	 * Rename this table
	 */
	public LiquidacionAsociado rename(String name) {
		return new LiquidacionAsociado(name, null);
	}
}
