/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.LiquidacionCalculoRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionCalculo extends TableImpl<LiquidacionCalculoRecord> {

	private static final long serialVersionUID = -2071274246;

	/**
	 * The reference instance of <code>public.liquidacion_calculo</code>
	 */
	public static final LiquidacionCalculo LIQUIDACION_CALCULO = new LiquidacionCalculo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LiquidacionCalculoRecord> getRecordType() {
		return LiquidacionCalculoRecord.class;
	}

	/**
	 * The column <code>public.liquidacion_calculo.grupo_id</code>.
	 */
	public final TableField<LiquidacionCalculoRecord, String> GRUPO_ID = createField("grupo_id", org.jooq.impl.SQLDataType.VARCHAR.length(3), this, "");

	/**
	 * The column <code>public.liquidacion_calculo.ronda_id</code>.
	 */
	public final TableField<LiquidacionCalculoRecord, Short> RONDA_ID = createField("ronda_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.liquidacion_calculo.liquidacion_id</code>.
	 */
	public final TableField<LiquidacionCalculoRecord, Integer> LIQUIDACION_ID = createField("liquidacion_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.liquidacion_calculo.activos</code>.
	 */
	public final TableField<LiquidacionCalculoRecord, Long> ACTIVOS = createField("activos", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.liquidacion_calculo.diferencia</code>.
	 */
	public final TableField<LiquidacionCalculoRecord, Long> DIFERENCIA = createField("diferencia", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.liquidacion_calculo.subtotal</code>.
	 */
	public final TableField<LiquidacionCalculoRecord, BigDecimal> SUBTOTAL = createField("subtotal", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>public.liquidacion_calculo.borrador</code>.
	 */
	public final TableField<LiquidacionCalculoRecord, Boolean> BORRADOR = createField("borrador", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.liquidacion_calculo</code> table reference
	 */
	public LiquidacionCalculo() {
		this("liquidacion_calculo", null);
	}

	/**
	 * Create an aliased <code>public.liquidacion_calculo</code> table reference
	 */
	public LiquidacionCalculo(String alias) {
		this(alias, LIQUIDACION_CALCULO);
	}

	private LiquidacionCalculo(String alias, Table<LiquidacionCalculoRecord> aliased) {
		this(alias, aliased, null);
	}

	private LiquidacionCalculo(String alias, Table<LiquidacionCalculoRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionCalculo as(String alias) {
		return new LiquidacionCalculo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public LiquidacionCalculo rename(String name) {
		return new LiquidacionCalculo(name, null);
	}
}
