/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.LiquidacionGruposRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionGrupos extends TableImpl<LiquidacionGruposRecord> {

	private static final long serialVersionUID = -1377329356;

	/**
	 * The reference instance of <code>public.liquidacion_grupos</code>
	 */
	public static final LiquidacionGrupos LIQUIDACION_GRUPOS = new LiquidacionGrupos();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LiquidacionGruposRecord> getRecordType() {
		return LiquidacionGruposRecord.class;
	}

	/**
	 * The column <code>public.liquidacion_grupos.ronda_etiqueta</code>.
	 */
	public final TableField<LiquidacionGruposRecord, String> RONDA_ETIQUETA = createField("ronda_etiqueta", org.jooq.impl.SQLDataType.VARCHAR.length(9), this, "");

	/**
	 * The column <code>public.liquidacion_grupos.ronda_id</code>.
	 */
	public final TableField<LiquidacionGruposRecord, Short> RONDA_ID = createField("ronda_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.liquidacion_grupos.grupo_id</code>.
	 */
	public final TableField<LiquidacionGruposRecord, String> GRUPO_ID = createField("grupo_id", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.liquidacion_grupos.nombre</code>.
	 */
	public final TableField<LiquidacionGruposRecord, String> NOMBRE = createField("nombre", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.liquidacion_grupos.activos</code>.
	 */
	public final TableField<LiquidacionGruposRecord, Long> ACTIVOS = createField("activos", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.liquidacion_grupos.asociacion</code>.
	 */
	public final TableField<LiquidacionGruposRecord, Integer> ASOCIACION = createField("asociacion", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.liquidacion_grupos.balance</code>.
	 */
	public final TableField<LiquidacionGruposRecord, BigDecimal> BALANCE = createField("balance", org.jooq.impl.SQLDataType.NUMERIC, this, "");

	/**
	 * The column <code>public.liquidacion_grupos.num_liquidaciones</code>.
	 */
	public final TableField<LiquidacionGruposRecord, Long> NUM_LIQUIDACIONES = createField("num_liquidaciones", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.liquidacion_grupos.activos_ultima</code>.
	 */
	public final TableField<LiquidacionGruposRecord, Long> ACTIVOS_ULTIMA = createField("activos_ultima", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.liquidacion_grupos.creado_en</code>.
	 */
	public final TableField<LiquidacionGruposRecord, Timestamp> CREADO_EN = createField("creado_en", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>public.liquidacion_grupos</code> table reference
	 */
	public LiquidacionGrupos() {
		this("liquidacion_grupos", null);
	}

	/**
	 * Create an aliased <code>public.liquidacion_grupos</code> table reference
	 */
	public LiquidacionGrupos(String alias) {
		this(alias, LIQUIDACION_GRUPOS);
	}

	private LiquidacionGrupos(String alias, Table<LiquidacionGruposRecord> aliased) {
		this(alias, aliased, null);
	}

	private LiquidacionGrupos(String alias, Table<LiquidacionGruposRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LiquidacionGrupos as(String alias) {
		return new LiquidacionGrupos(alias, this);
	}

	/**
	 * Rename this table
	 */
	public LiquidacionGrupos rename(String name) {
		return new LiquidacionGrupos(name, null);
	}
}
