/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Keys;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.RondaRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ronda extends TableImpl<RondaRecord> {

	private static final long serialVersionUID = -1736926648;

	/**
	 * The reference instance of <code>public.ronda</code>
	 */
	public static final Ronda RONDA = new Ronda();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RondaRecord> getRecordType() {
		return RondaRecord.class;
	}

	/**
	 * The column <code>public.ronda.id</code>.
	 */
	public final TableField<RondaRecord, Short> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.ronda.etiqueta</code>.
	 */
	public final TableField<RondaRecord, String> ETIQUETA = createField("etiqueta", org.jooq.impl.SQLDataType.VARCHAR.length(9).nullable(false), this, "");

	/**
	 * The column <code>public.ronda.rango</code>.
	 */
	public final TableField<RondaRecord, Object> RANGO = createField("rango", org.jooq.impl.DefaultDataType.getDefaultDataType("daterange"), this, "");

	/**
	 * Create a <code>public.ronda</code> table reference
	 */
	public Ronda() {
		this("ronda", null);
	}

	/**
	 * Create an aliased <code>public.ronda</code> table reference
	 */
	public Ronda(String alias) {
		this(alias, RONDA);
	}

	private Ronda(String alias, Table<RondaRecord> aliased) {
		this(alias, aliased, null);
	}

	private Ronda(String alias, Table<RondaRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RondaRecord> getPrimaryKey() {
		return Keys.PK_RONDA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RondaRecord>> getKeys() {
		return Arrays.<UniqueKey<RondaRecord>>asList(Keys.PK_RONDA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Ronda as(String alias) {
		return new Ronda(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Ronda rename(String name) {
		return new Ronda(name, null);
	}
}
