/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.ValoresPorLiquidacionRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValoresPorLiquidacion extends TableImpl<ValoresPorLiquidacionRecord> {

	private static final long serialVersionUID = -1441502375;

	/**
	 * The reference instance of <code>public.valores_por_liquidacion</code>
	 */
	public static final ValoresPorLiquidacion VALORES_POR_LIQUIDACION = new ValoresPorLiquidacion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ValoresPorLiquidacionRecord> getRecordType() {
		return ValoresPorLiquidacionRecord.class;
	}

	/**
	 * The column <code>public.valores_por_liquidacion.ambito</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, String> AMBITO = createField("ambito", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.especificidad</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Integer> ESPECIFICIDAD = createField("especificidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.joven</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> JOVEN = createField("joven", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.kraal</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> KRAAL = createField("kraal", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.comite</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> COMITE = createField("comite", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.colonia</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> COLONIA = createField("colonia", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.manada</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> MANADA = createField("manada", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.exploradores</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> EXPLORADORES = createField("exploradores", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.expedicion</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> EXPEDICION = createField("expedicion", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.ruta</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> RUTA = createField("ruta", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.total</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Long> TOTAL = createField("total", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_por_liquidacion.liquidacion_id</code>.
	 */
	public final TableField<ValoresPorLiquidacionRecord, Integer> LIQUIDACION_ID = createField("liquidacion_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.valores_por_liquidacion</code> table reference
	 */
	public ValoresPorLiquidacion() {
		this("valores_por_liquidacion", null);
	}

	/**
	 * Create an aliased <code>public.valores_por_liquidacion</code> table reference
	 */
	public ValoresPorLiquidacion(String alias) {
		this(alias, VALORES_POR_LIQUIDACION);
	}

	private ValoresPorLiquidacion(String alias, Table<ValoresPorLiquidacionRecord> aliased) {
		this(alias, aliased, null);
	}

	private ValoresPorLiquidacion(String alias, Table<ValoresPorLiquidacionRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresPorLiquidacion as(String alias) {
		return new ValoresPorLiquidacion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ValoresPorLiquidacion rename(String name) {
		return new ValoresPorLiquidacion(name, null);
	}
}
