/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;
import org.scoutsfev.cudu.db.Public;
import org.scoutsfev.cudu.db.tables.records.ValoresFederativosRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValoresFederativos extends TableImpl<ValoresFederativosRecord> {

	private static final long serialVersionUID = 147030720;

	/**
	 * The reference instance of <code>public.valores_federativos</code>
	 */
	public static final ValoresFederativos VALORES_FEDERATIVOS = new ValoresFederativos();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ValoresFederativosRecord> getRecordType() {
		return ValoresFederativosRecord.class;
	}

	/**
	 * The column <code>public.valores_federativos.ambito</code>.
	 */
	public final TableField<ValoresFederativosRecord, Object> AMBITO = createField("ambito", org.jooq.impl.DefaultDataType.getDefaultDataType("unknown"), this, "");

	/**
	 * The column <code>public.valores_federativos.especificidad</code>.
	 */
	public final TableField<ValoresFederativosRecord, Integer> ESPECIFICIDAD = createField("especificidad", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.valores_federativos.joven</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> JOVEN = createField("joven", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.kraal</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> KRAAL = createField("kraal", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.comite</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> COMITE = createField("comite", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.colonia</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> COLONIA = createField("colonia", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.manada</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> MANADA = createField("manada", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.exploradores</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> EXPLORADORES = createField("exploradores", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.expedicion</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> EXPEDICION = createField("expedicion", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.ruta</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> RUTA = createField("ruta", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.valores_federativos.total</code>.
	 */
	public final TableField<ValoresFederativosRecord, Long> TOTAL = createField("total", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.valores_federativos</code> table reference
	 */
	public ValoresFederativos() {
		this("valores_federativos", null);
	}

	/**
	 * Create an aliased <code>public.valores_federativos</code> table reference
	 */
	public ValoresFederativos(String alias) {
		this(alias, VALORES_FEDERATIVOS);
	}

	private ValoresFederativos(String alias, Table<ValoresFederativosRecord> aliased) {
		this(alias, aliased, null);
	}

	private ValoresFederativos(String alias, Table<ValoresFederativosRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ValoresFederativos as(String alias) {
		return new ValoresFederativos(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ValoresFederativos rename(String name) {
		return new ValoresFederativos(name, null);
	}
}
