/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Curso implements Serializable {

	private static final long serialVersionUID = 1707815234;

	private final Integer   id;
	private final String    titulo;
	private final Timestamp fechaInicioInscripcion;
	private final Timestamp fechaFinInscripcion;
	private final Date      fechaNacimientoMinima;
	private final Integer   plazas;
	private final String    descripcionFechas;
	private final String    descripcionLugar;
	private final Boolean   visible;
	private final Integer   coordinadorId;

	public Curso(Curso value) {
		this.id = value.id;
		this.titulo = value.titulo;
		this.fechaInicioInscripcion = value.fechaInicioInscripcion;
		this.fechaFinInscripcion = value.fechaFinInscripcion;
		this.fechaNacimientoMinima = value.fechaNacimientoMinima;
		this.plazas = value.plazas;
		this.descripcionFechas = value.descripcionFechas;
		this.descripcionLugar = value.descripcionLugar;
		this.visible = value.visible;
		this.coordinadorId = value.coordinadorId;
	}

	public Curso(
		Integer   id,
		String    titulo,
		Timestamp fechaInicioInscripcion,
		Timestamp fechaFinInscripcion,
		Date      fechaNacimientoMinima,
		Integer   plazas,
		String    descripcionFechas,
		String    descripcionLugar,
		Boolean   visible,
		Integer   coordinadorId
	) {
		this.id = id;
		this.titulo = titulo;
		this.fechaInicioInscripcion = fechaInicioInscripcion;
		this.fechaFinInscripcion = fechaFinInscripcion;
		this.fechaNacimientoMinima = fechaNacimientoMinima;
		this.plazas = plazas;
		this.descripcionFechas = descripcionFechas;
		this.descripcionLugar = descripcionLugar;
		this.visible = visible;
		this.coordinadorId = coordinadorId;
	}

	public Integer getId() {
		return this.id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public Timestamp getFechaInicioInscripcion() {
		return this.fechaInicioInscripcion;
	}

	public Timestamp getFechaFinInscripcion() {
		return this.fechaFinInscripcion;
	}

	public Date getFechaNacimientoMinima() {
		return this.fechaNacimientoMinima;
	}

	public Integer getPlazas() {
		return this.plazas;
	}

	public String getDescripcionFechas() {
		return this.descripcionFechas;
	}

	public String getDescripcionLugar() {
		return this.descripcionLugar;
	}

	public Boolean getVisible() {
		return this.visible;
	}

	public Integer getCoordinadorId() {
		return this.coordinadorId;
	}
}
