/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoDatosRamaTipo implements Serializable {

	private static final long serialVersionUID = -1034408940;

	private final Boolean esJoven;
	private final Long    colonia;
	private final Long    manada;
	private final Long    exploradores;
	private final Long    expedicion;
	private final Long    ruta;
	private final Long    total;

	public DtoDatosRamaTipo(DtoDatosRamaTipo value) {
		this.esJoven = value.esJoven;
		this.colonia = value.colonia;
		this.manada = value.manada;
		this.exploradores = value.exploradores;
		this.expedicion = value.expedicion;
		this.ruta = value.ruta;
		this.total = value.total;
	}

	public DtoDatosRamaTipo(
		Boolean esJoven,
		Long    colonia,
		Long    manada,
		Long    exploradores,
		Long    expedicion,
		Long    ruta,
		Long    total
	) {
		this.esJoven = esJoven;
		this.colonia = colonia;
		this.manada = manada;
		this.exploradores = exploradores;
		this.expedicion = expedicion;
		this.ruta = ruta;
		this.total = total;
	}

	public Boolean getEsJoven() {
		return this.esJoven;
	}

	public Long getColonia() {
		return this.colonia;
	}

	public Long getManada() {
		return this.manada;
	}

	public Long getExploradores() {
		return this.exploradores;
	}

	public Long getExpedicion() {
		return this.expedicion;
	}

	public Long getRuta() {
		return this.ruta;
	}

	public Long getTotal() {
		return this.total;
	}
}
