/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DtoMiembrosCurso implements Serializable {

	private static final long serialVersionUID = 432127687;

	private final Integer cursoId;
	private final Integer id;
	private final String  tipoMiembro;
	private final Integer secuenciaInscripcion;
	private final String  tipo;
	private final String  nombreCompleto;
	private final String  nombreGrupo;
	private final String  telefono;
	private final String  email;
	private final Date    fechaNacimiento;

	public DtoMiembrosCurso(DtoMiembrosCurso value) {
		this.cursoId = value.cursoId;
		this.id = value.id;
		this.tipoMiembro = value.tipoMiembro;
		this.secuenciaInscripcion = value.secuenciaInscripcion;
		this.tipo = value.tipo;
		this.nombreCompleto = value.nombreCompleto;
		this.nombreGrupo = value.nombreGrupo;
		this.telefono = value.telefono;
		this.email = value.email;
		this.fechaNacimiento = value.fechaNacimiento;
	}

	public DtoMiembrosCurso(
		Integer cursoId,
		Integer id,
		String  tipoMiembro,
		Integer secuenciaInscripcion,
		String  tipo,
		String  nombreCompleto,
		String  nombreGrupo,
		String  telefono,
		String  email,
		Date    fechaNacimiento
	) {
		this.cursoId = cursoId;
		this.id = id;
		this.tipoMiembro = tipoMiembro;
		this.secuenciaInscripcion = secuenciaInscripcion;
		this.tipo = tipo;
		this.nombreCompleto = nombreCompleto;
		this.nombreGrupo = nombreGrupo;
		this.telefono = telefono;
		this.email = email;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Integer getCursoId() {
		return this.cursoId;
	}

	public Integer getId() {
		return this.id;
	}

	public String getTipoMiembro() {
		return this.tipoMiembro;
	}

	public Integer getSecuenciaInscripcion() {
		return this.secuenciaInscripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public String getNombreCompleto() {
		return this.nombreCompleto;
	}

	public String getNombreGrupo() {
		return this.nombreGrupo;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}
}
