/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InformacionPago implements Serializable {

	private static final long serialVersionUID = 1115343939;

	private final Integer    asociacionid;
	private final String     titular;
	private final String     iban;
	private final BigDecimal precioporasociado;

	public InformacionPago(InformacionPago value) {
		this.asociacionid = value.asociacionid;
		this.titular = value.titular;
		this.iban = value.iban;
		this.precioporasociado = value.precioporasociado;
	}

	public InformacionPago(
		Integer    asociacionid,
		String     titular,
		String     iban,
		BigDecimal precioporasociado
	) {
		this.asociacionid = asociacionid;
		this.titular = titular;
		this.iban = iban;
		this.precioporasociado = precioporasociado;
	}

	public Integer getAsociacionid() {
		return this.asociacionid;
	}

	public String getTitular() {
		return this.titular;
	}

	public String getIban() {
		return this.iban;
	}

	public BigDecimal getPrecioporasociado() {
		return this.precioporasociado;
	}
}
