/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionGrupos implements Serializable {

	private static final long serialVersionUID = -2068963470;

	private final String     rondaEtiqueta;
	private final Double     rondaId;
	private final String     grupoId;
	private final String     nombre;
	private final Long       activos;
	private final Integer    asociacion;
	private final BigDecimal balance;
	private final Long       numLiquidaciones;
	private final Long       activosUltima;

	public LiquidacionGrupos(LiquidacionGrupos value) {
		this.rondaEtiqueta = value.rondaEtiqueta;
		this.rondaId = value.rondaId;
		this.grupoId = value.grupoId;
		this.nombre = value.nombre;
		this.activos = value.activos;
		this.asociacion = value.asociacion;
		this.balance = value.balance;
		this.numLiquidaciones = value.numLiquidaciones;
		this.activosUltima = value.activosUltima;
	}

	public LiquidacionGrupos(
		String     rondaEtiqueta,
		Double     rondaId,
		String     grupoId,
		String     nombre,
		Long       activos,
		Integer    asociacion,
		BigDecimal balance,
		Long       numLiquidaciones,
		Long       activosUltima
	) {
		this.rondaEtiqueta = rondaEtiqueta;
		this.rondaId = rondaId;
		this.grupoId = grupoId;
		this.nombre = nombre;
		this.activos = activos;
		this.asociacion = asociacion;
		this.balance = balance;
		this.numLiquidaciones = numLiquidaciones;
		this.activosUltima = activosUltima;
	}

	public String getRondaEtiqueta() {
		return this.rondaEtiqueta;
	}

	public Double getRondaId() {
		return this.rondaId;
	}

	public String getGrupoId() {
		return this.grupoId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public Long getActivos() {
		return this.activos;
	}

	public Integer getAsociacion() {
		return this.asociacion;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public Long getNumLiquidaciones() {
		return this.numLiquidaciones;
	}

	public Long getActivosUltima() {
		return this.activosUltima;
	}
}
