/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionBalance implements Serializable {

	private static final long serialVersionUID = -697812588;

	private final String     grupoId;
	private final Short      rondaId;
	private final Integer    liquidacionId;
	private final Long       activos;
	private final Long       diferencia;
	private final BigDecimal precioUnitario;
	private final BigDecimal subtotal;
	private final BigDecimal ajusteManual;
	private final BigDecimal pagado;
	private final BigDecimal balance;

	public LiquidacionBalance(LiquidacionBalance value) {
		this.grupoId = value.grupoId;
		this.rondaId = value.rondaId;
		this.liquidacionId = value.liquidacionId;
		this.activos = value.activos;
		this.diferencia = value.diferencia;
		this.precioUnitario = value.precioUnitario;
		this.subtotal = value.subtotal;
		this.ajusteManual = value.ajusteManual;
		this.pagado = value.pagado;
		this.balance = value.balance;
	}

	public LiquidacionBalance(
		String     grupoId,
		Short      rondaId,
		Integer    liquidacionId,
		Long       activos,
		Long       diferencia,
		BigDecimal precioUnitario,
		BigDecimal subtotal,
		BigDecimal ajusteManual,
		BigDecimal pagado,
		BigDecimal balance
	) {
		this.grupoId = grupoId;
		this.rondaId = rondaId;
		this.liquidacionId = liquidacionId;
		this.activos = activos;
		this.diferencia = diferencia;
		this.precioUnitario = precioUnitario;
		this.subtotal = subtotal;
		this.ajusteManual = ajusteManual;
		this.pagado = pagado;
		this.balance = balance;
	}

	public String getGrupoId() {
		return this.grupoId;
	}

	public Short getRondaId() {
		return this.rondaId;
	}

	public Integer getLiquidacionId() {
		return this.liquidacionId;
	}

	public Long getActivos() {
		return this.activos;
	}

	public Long getDiferencia() {
		return this.diferencia;
	}

	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public BigDecimal getAjusteManual() {
		return this.ajusteManual;
	}

	public BigDecimal getPagado() {
		return this.pagado;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}
}
