/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionAsociado implements Serializable {

	private static final long serialVersionUID = 211323733;

	private final Integer   liquidacionId;
	private final Integer   asociadoId;
	private final Boolean   alta;
	private final Timestamp creadoEn;

	public LiquidacionAsociado(LiquidacionAsociado value) {
		this.liquidacionId = value.liquidacionId;
		this.asociadoId = value.asociadoId;
		this.alta = value.alta;
		this.creadoEn = value.creadoEn;
	}

	public LiquidacionAsociado(
		Integer   liquidacionId,
		Integer   asociadoId,
		Boolean   alta,
		Timestamp creadoEn
	) {
		this.liquidacionId = liquidacionId;
		this.asociadoId = asociadoId;
		this.alta = alta;
		this.creadoEn = creadoEn;
	}

	public Integer getLiquidacionId() {
		return this.liquidacionId;
	}

	public Integer getAsociadoId() {
		return this.asociadoId;
	}

	public Boolean getAlta() {
		return this.alta;
	}

	public Timestamp getCreadoEn() {
		return this.creadoEn;
	}
}
