/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Liquidacion implements Serializable {

	private static final long serialVersionUID = 481033019;

	private final Integer    id;
	private final String     grupoId;
	private final Short      rondaId;
	private final Boolean    borrador;
	private final BigDecimal ajusteManual;
	private final BigDecimal pagado;
	private final Timestamp  fechaPago;
	private final BigDecimal precioUnitario;
	private final String     creadoPor;
	private final Timestamp  creadoEn;
	private final String     observaciones;

	public Liquidacion(Liquidacion value) {
		this.id = value.id;
		this.grupoId = value.grupoId;
		this.rondaId = value.rondaId;
		this.borrador = value.borrador;
		this.ajusteManual = value.ajusteManual;
		this.pagado = value.pagado;
		this.fechaPago = value.fechaPago;
		this.precioUnitario = value.precioUnitario;
		this.creadoPor = value.creadoPor;
		this.creadoEn = value.creadoEn;
		this.observaciones = value.observaciones;
	}

	public Liquidacion(
		Integer    id,
		String     grupoId,
		Short      rondaId,
		Boolean    borrador,
		BigDecimal ajusteManual,
		BigDecimal pagado,
		Timestamp  fechaPago,
		BigDecimal precioUnitario,
		String     creadoPor,
		Timestamp  creadoEn,
		String     observaciones
	) {
		this.id = id;
		this.grupoId = grupoId;
		this.rondaId = rondaId;
		this.borrador = borrador;
		this.ajusteManual = ajusteManual;
		this.pagado = pagado;
		this.fechaPago = fechaPago;
		this.precioUnitario = precioUnitario;
		this.creadoPor = creadoPor;
		this.creadoEn = creadoEn;
		this.observaciones = observaciones;
	}

	public Integer getId() {
		return this.id;
	}

	public String getGrupoId() {
		return this.grupoId;
	}

	public Short getRondaId() {
		return this.rondaId;
	}

	public Boolean getBorrador() {
		return this.borrador;
	}

	public BigDecimal getAjusteManual() {
		return this.ajusteManual;
	}

	public BigDecimal getPagado() {
		return this.pagado;
	}

	public Timestamp getFechaPago() {
		return this.fechaPago;
	}

	public BigDecimal getPrecioUnitario() {
		return this.precioUnitario;
	}

	public String getCreadoPor() {
		return this.creadoPor;
	}

	public Timestamp getCreadoEn() {
		return this.creadoEn;
	}

	public String getObservaciones() {
		return this.observaciones;
	}
}
