/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LiquidacionCalculo implements Serializable {

	private static final long serialVersionUID = 2089046120;

	private final String     grupoId;
	private final Short      rondaId;
	private final Integer    liquidacionId;
	private final Long       activos;
	private final Long       diferencia;
	private final BigDecimal subtotal;

	public LiquidacionCalculo(LiquidacionCalculo value) {
		this.grupoId = value.grupoId;
		this.rondaId = value.rondaId;
		this.liquidacionId = value.liquidacionId;
		this.activos = value.activos;
		this.diferencia = value.diferencia;
		this.subtotal = value.subtotal;
	}

	public LiquidacionCalculo(
		String     grupoId,
		Short      rondaId,
		Integer    liquidacionId,
		Long       activos,
		Long       diferencia,
		BigDecimal subtotal
	) {
		this.grupoId = grupoId;
		this.rondaId = rondaId;
		this.liquidacionId = liquidacionId;
		this.activos = activos;
		this.diferencia = diferencia;
		this.subtotal = subtotal;
	}

	public String getGrupoId() {
		return this.grupoId;
	}

	public Short getRondaId() {
		return this.rondaId;
	}

	public Integer getLiquidacionId() {
		return this.liquidacionId;
	}

	public Long getActivos() {
		return this.activos;
	}

	public Long getDiferencia() {
		return this.diferencia;
	}

	public BigDecimal getSubtotal() {
		return this.subtotal;
	}
}
