/**
 * This class is generated by jOOQ
 */
package org.scoutsfev.cudu.db.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaVersion implements Serializable {

	private static final long serialVersionUID = 1089817877;

	private final Integer   versionRank;
	private final Integer   installedRank;
	private final String    version;
	private final String    description;
	private final String    type;
	private final String    script;
	private final Integer   checksum;
	private final String    installedBy;
	private final Timestamp installedOn;
	private final Integer   executionTime;
	private final Boolean   success;

	public SchemaVersion(SchemaVersion value) {
		this.versionRank = value.versionRank;
		this.installedRank = value.installedRank;
		this.version = value.version;
		this.description = value.description;
		this.type = value.type;
		this.script = value.script;
		this.checksum = value.checksum;
		this.installedBy = value.installedBy;
		this.installedOn = value.installedOn;
		this.executionTime = value.executionTime;
		this.success = value.success;
	}

	public SchemaVersion(
		Integer   versionRank,
		Integer   installedRank,
		String    version,
		String    description,
		String    type,
		String    script,
		Integer   checksum,
		String    installedBy,
		Timestamp installedOn,
		Integer   executionTime,
		Boolean   success
	) {
		this.versionRank = versionRank;
		this.installedRank = installedRank;
		this.version = version;
		this.description = description;
		this.type = type;
		this.script = script;
		this.checksum = checksum;
		this.installedBy = installedBy;
		this.installedOn = installedOn;
		this.executionTime = executionTime;
		this.success = success;
	}

	public Integer getVersionRank() {
		return this.versionRank;
	}

	public Integer getInstalledRank() {
		return this.installedRank;
	}

	public String getVersion() {
		return this.version;
	}

	public String getDescription() {
		return this.description;
	}

	public String getType() {
		return this.type;
	}

	public String getScript() {
		return this.script;
	}

	public Integer getChecksum() {
		return this.checksum;
	}

	public String getInstalledBy() {
		return this.installedBy;
	}

	public Timestamp getInstalledOn() {
		return this.installedOn;
	}

	public Integer getExecutionTime() {
		return this.executionTime;
	}

	public Boolean getSuccess() {
		return this.success;
	}
}
